Task av/j95 timestamp comment functionality
BinaryStudioAcademy/bsa-2021-jabber pull request #111
Opened 2021-08-09 14:05 UTC by artem-totality

2021-08-09 15:29 UTC, JuliaDzyuba approved these changes, later dismissed

2021-08-09 16:01 UTC, ZubkoWhatislove requested changes

2021-08-09 16:01 UTC, ZubkoWhatislove commented on backend/src/api/records/records.api.ts
> +  recordRouter.get(
remove records api at all
you need to join record into episode

2021-08-09 16:01 UTC, ZubkoWhatislove commented on backend/src/data/repositories/record/record.repository.ts
> +  }
```suggestion
```

2021-08-09 16:01 UTC, ZubkoWhatislove commented on backend/src/services/record/record.service.ts
> +    return record;
```suggestion
```

2021-08-10 04:18 UTC, ZubkoWhatislove requested changes

2021-08-10 04:18 UTC, ZubkoWhatislove commented on frontend/src/components/episode/episode.tsx
> +          ) : null}
```suggestion
          {episode.record && (
            <Player src={episode.record.fileUrl} setRef={setPlayer} />
          )}
```

2021-08-10 04:18 UTC, ZubkoWhatislove commented on frontend/src/components/episode/episode.tsx
> +import { Player } from 'components/common/common';
we already have imports from components

2021-08-10 04:18 UTC, ZubkoWhatislove commented on frontend/src/components/episode/episode.tsx
> +  const [player, setPlayer] = useState<H5AudioPlayer | null>(null);
```suggestion
  const [player, setPlayer] = useState<H5AudioPlayer | null>(null);
```
use useRef instead

2021-08-10 04:18 UTC, ZubkoWhatislove commented on frontend/src/components/episode/episode.tsx
> +      player && player.audio.current
```suggestion
      Boolean(player?.audio.current)
```

2021-08-10 04:18 UTC, ZubkoWhatislove commented on frontend/src/components/episode/episode.tsx
> +    const timestamp =
move this calculation to helper `frontend/src/components/episode/helpers/`

2021-08-10 14:37 UTC, ZubkoWhatislove requested changes

2021-08-10 14:37 UTC, ZubkoWhatislove commented on frontend/src/components/episode/helpers/get-current-time.helper.ts
> +    : 0;
```suggestion
const DEFAULT_TIME = 0;

const getCurrentTime = (playerRef: React.MutableRefObject<PlayerRef | null>): number => {
  return playerRef.current
    ? Math.round(playerRef.current?.getCurrentTime())
    : DEFAULT_TIME;
```

2021-08-10 14:37 UTC, ZubkoWhatislove commented on frontend/src/components/episode/helpers/get-current-time.helper.ts
> +import { PlayerRef } from 'components/common/player/player';
rename to `frontend/src/components/episode/helpers/get-current-time/get-current-time.helper.ts`

2021-08-10 17:00 UTC, Denidzio submitted a review, later dismissed

2021-08-10 17:27 UTC, Denidzio commented on frontend/src/components/episode/helpers/get-current-time/get-current-time.helper.ts
> +  const DEFAULT_TIME = 0;
It would be better to move the constant out of the function

2021-08-10 17:46 UTC, Denidzio approved these changes

2021-08-11 04:27 UTC, ZubkoWhatislove approved these changes

2021-08-11 04:27 UTC, merged