Task ys/j108 add my podcasts page
BinaryStudioAcademy/bsa-2021-jabber pull request #127
Opened 2021-08-10 21:41 UTC by yaroslav207

2021-08-11 04:36 UTC, ZubkoWhatislove requested changes

2021-08-11 04:36 UTC, ZubkoWhatislove commented on shared/src/common/enums/api/podcasts-api-path.enum.ts
> +  USER_$ID = '/user/:id',
```suggestion
  USERS = '/users',
  USERS_$ID = '/users/:id',
```

2021-08-11 04:36 UTC, ZubkoWhatislove commented on frontend/src/services/podcast-api/podcast-api.service.ts
> +  public getPodcastsByUserId(userId: number): Promise<Podcast[]> {
```suggestion
  public getAllByUserId(userId: number): Promise<Podcast[]> {
```

2021-08-11 04:36 UTC, ZubkoWhatislove commented on backend/src/services/podcast/podcast.service.ts
> +    return this.#podcastRepository.getPodcastsByUserId(userId);
```suggestion
  public getAllByUserId(userId: string): Promise<TPodcast[]> {
    return this.#podcastRepository.getAllByUserId(userId);
```

2021-08-11 04:36 UTC, ZubkoWhatislove commented on backend/src/data/repositories/podcast/podcast.repository.ts
> +  public getPodcastsByUserId(userId: string): Promise<TPodcast[]> {
```suggestion
  public getAllByUserId(userId: string): Promise<TPodcast[]> {
```

2021-08-11 07:09 UTC, yevhenprybytok submitted a review, later dismissed

2021-08-11 08:12 UTC, ZubkoWhatislove requested changes

2021-08-11 08:12 UTC, ZubkoWhatislove commented on shared/src/common/enums/api/podcasts-api-path.enum.ts
> +  USER_$ID = '/users/:id',
```suggestion
  USERS = '/users',
  USERS_$ID = '/users/:id',
```

2021-08-11 08:12 UTC, ZubkoWhatislove commented on frontend/src/services/podcast-api/podcast-api.service.ts
> +      `${this.#apiPrefix}${ApiPath.PODCASTS}${PodcastsApiPath.USER}${userId}`,
```suggestion
      `${this.#apiPrefix}${ApiPath.PODCASTS}${PodcastsApiPath.USER}/${userId}`,
```
🤔

2021-08-11 09:49 UTC, ZubkoWhatislove requested changes
add output podcast functionality for user-profile page

2021-08-11 12:47 UTC, ZubkoWhatislove requested changes

2021-08-11 12:47 UTC, ghost commented on frontend/src/components/user-profile/user-profile.tsx
> +          : podcasts ? (
podcasts is an array. array is always true

2021-08-11 12:47 UTC, ghost commented on frontend/src/components/user-profile/user-profile.tsx
> +  const { user, podcasts, dataStatus } = useAppSelector(({ auth, userProfile }: RootState) => ({
you need to fetch user for this page

2021-08-11 13:09 UTC, yaroslav207 commented on frontend/src/components/user-profile/user-profile.tsx
> +  const { user, podcasts, dataStatus } = useAppSelector(({ auth, userProfile }: RootState) => ({
> you need to fetch user for this page

I didn't quite understand.
We get user from the store.

2021-08-12 04:32 UTC, ZubkoWhatislove commented on frontend/src/components/user-profile/user-profile.tsx
> +  const { user, podcasts, dataStatus } = useAppSelector(({ auth, userProfile }: RootState) => ({
you need to create user service, reducer and etc 🙂
this page will be public

2021-08-12 06:59 UTC, ghost approved these changes

2021-08-12 06:59 UTC, ZubkoWhatislove commented on backend/src/api/users/users.api.ts
> +    handleAsyncApi(async (_req, res) => {
```suggestion
    handleAsyncApi(async (req, res) => {
```
underscore only for unused params

2021-08-12 06:59 UTC, merged