Task dl/j118 edit timelines functionality
BinaryStudioAcademy/bsa-2021-jabber pull request #131
Opened 2021-08-11 11:29 UTC by Denidzio

2021-08-11 11:30 UTC, Denidzio commented
![](https://github.trello.services/images/mini-trello-icon.png) [Edit timelines functionality](https://trello.com/c/yzk1fhoQ/118-edit-timelines-functionality)

2021-08-11 15:41 UTC, JuliaDzyuba submitted a review, later dismissed

2021-08-12 04:37 UTC, ZubkoWhatislove requested changes

2021-08-12 04:37 UTC, ghost commented on frontend/src/components/configurate-episode/helpers/map-episode-to-form-payload/map-episode-to-form-payload.ts
>    status: EpisodeStatus.STAGING,
```suggestion
  status: episode.status,
```

2021-08-12 06:56 UTC, ZubkoWhatislove approved these changes

2021-08-12 06:56 UTC, merged