J-123: + create users_notifications migration
BinaryStudioAcademy/bsa-2021-jabber pull request #132
Opened 2021-08-11 12:58 UTC by artem-totality

2021-08-11 14:32 UTC, ZubkoWhatislove requested changes

2021-08-11 14:32 UTC, ghost commented on backend/src/data/migrations/20210811124705_add_users_notifications_table.ts
> +import { Knex } from 'knex';
don't forget about model, types and etc

2021-08-11 14:32 UTC, ghost commented on backend/src/data/migrations/20210811124705_add_users_notifications_table.ts
> +    table.boolean('is_checked').notNullable().defaultTo(false);
we have enum here? 🤔

2021-08-11 15:15 UTC, artem-totality commented on backend/src/data/migrations/20210811124705_add_users_notifications_table.ts
> +    table.boolean('is_checked').notNullable().defaultTo(false);
No, we have not used any enums before

2021-08-12 04:39 UTC, ZubkoWhatislove requested changes

2021-08-12 04:39 UTC, ZubkoWhatislove commented on backend/src/data/migrations/20210811124705_add_users_notifications_table.ts
> +    table.boolean('is_checked').notNullable().defaultTo(false);
We don't have any flags in this entity
![image](https://user-images.githubusercontent.com/60396171/129139016-329b1f57-6f2e-4a68-a47f-4529b8b5bf7f.png)
check your task

2021-08-12 06:19 UTC, ZubkoWhatislove requested changes

2021-08-12 06:19 UTC, ZubkoWhatislove commented on backend/src/data/migrations/20210811124705_add_users_notifications_table.ts
> +import { UserNotificationStatus } from '~/common/enums/enums';
```suggestion
```
create a new enum inside migration

2021-08-12 06:57 UTC, ZubkoWhatislove approved these changes

2021-08-12 06:57 UTC, merged