Task jd/j109 add markup for live page
BinaryStudioAcademy/bsa-2021-jabber pull request #133
Opened 2021-08-11 15:22 UTC by JuliaDzyuba

2021-08-11 15:42 UTC, JuliaDzyuba commented
editing episode markup will be in a different branch (ticket 121)

2021-08-11 15:44 UTC, Denidzio commented on frontend/src/components/podcast-live/podcast-live.tsx
> +    alert(payload.text);
Why you use 'alert' here?

2021-08-12 04:42 UTC, ZubkoWhatislove requested changes

2021-08-12 04:42 UTC, ZubkoWhatislove commented on frontend/src/components/app/app.tsx
> +        <AuthPublicRouter
remove an old route for podcast live

2021-08-12 04:42 UTC, ZubkoWhatislove commented on frontend/src/components/common/common.ts
> +export { default as Comment } from './comment/comment';
```suggestion
export { default as CommentItem } from './comment-item/comment-item';
```

2021-08-12 04:42 UTC, ZubkoWhatislove commented on frontend/src/components/episode/episode.tsx
> +                isStaging && isOwner && <Button label={'Start Live'} href={`${AppRoute.EPISODES}/${id}${AppRoute.LIVE}`}/>
```suggestion
                isStaging && isOwner && <Button label="Start Live" href={`${AppRoute.EPISODES}/${id}${AppRoute.LIVE}`}/>
```

2021-08-12 04:42 UTC, ZubkoWhatislove commented on frontend/src/components/app/app.tsx
> +          component={PodcastLive}
```suggestion
          component={EpisodeLive}
```

2021-08-12 04:42 UTC, ZubkoWhatislove commented on frontend/src/components/podcast-live/podcast-live.tsx
>  const PodcastLive: React.FC = () => {
```suggestion
const EpisodeLive: React.FC = () => {
```

2021-08-12 04:42 UTC, ZubkoWhatislove commented on frontend/src/components/podcast-live/podcast-live.tsx
> -import { useAppSelector, useDispatch, useEffect } from 'hooks/hooks';
rename file to `frontend/src/components/episode-live/episode-live.tsx`

2021-08-12 08:05 UTC, ZubkoWhatislove approved these changes

2021-08-12 08:05 UTC, merged