Task sf/j92 add socketio for comments
BinaryStudioAcademy/bsa-2021-jabber pull request #134
Opened 2021-08-11 16:46 UTC by Sayonarko

2021-08-11 19:01 UTC, JuliaDzyuba submitted a review, later dismissed

2021-08-11 19:57 UTC, Denidzio submitted a review, later dismissed

2021-08-12 04:31 UTC, ZubkoWhatislove requested changes

2021-08-12 04:31 UTC, ZubkoWhatislove commented on backend/src/middlewares/socket-injector/socket-injector.middleware.ts
> +export { socketInjector };
```suggestion
export { socketInjector };

```

2021-08-12 04:31 UTC, ZubkoWhatislove commented on backend/src/middlewares/middlewares.ts
> +export { socketInjector } from './socket-injector/socket-injector.middleware';
```suggestion
export { injectSocket } from './inject-socket/inject-socket.middleware';
```

2021-08-12 04:31 UTC, ZubkoWhatislove commented on shared/src/common/enums/socket/socket-event.enum.ts
> +export { SocketEvent };
```suggestion
export { SocketEvent };

```

2021-08-12 04:31 UTC, ZubkoWhatislove commented on frontend/src/components/episode/episode.tsx
> +    socketService.getUpdatedComments(dispatch, episodeActions.updateComments);
```suggestion
```
we don't want to do it directly in the components
consider using packages for the redux to do it in the middleware

2021-08-12 16:14 UTC, ZubkoWhatislove requested changes

2021-08-12 16:14 UTC, ZubkoWhatislove commented on backend/src/middlewares/inject-socket/inject-socket.middleware.ts
> +  next();
```suggestion
  return next();
```

2021-08-12 16:14 UTC, ZubkoWhatislove commented on frontend/src/middlewares/middlewares.ts
> +export { socketMiddleware } from './socket/socket.middleware';
```suggestion
export { socket } from './socket/socket.middleware';
```

2021-08-12 16:14 UTC, ZubkoWhatislove commented on frontend/src/middlewares/socket/socket.middleware.ts
> +const socketMiddleware: Middleware = ({ dispatch }) => (next): Next => {
```suggestion
const socket: Middleware = ({ dispatch }) => (next): Next => {
```

2021-08-12 16:14 UTC, ZubkoWhatislove commented on frontend/src/middlewares/socket/socket.middleware.ts
> +const socketMiddleware: Middleware = ({ dispatch }) => (next): Next => {
```suggestion
const socket = io(ENV.SOCKET_SERVER);

const socketMiddleware: Middleware = ({ dispatch }) => (next) => {
```
we really need it? 🤔

2021-08-12 16:14 UTC, ZubkoWhatislove commented on frontend/src/store/store.ts
> +import { handleError as handleErrorMiddleware, socketMiddleware } from 'middlewares/middlewares';
```suggestion
import { handleError as handleErrorMiddleware, socket as socketMiddleware } from 'middlewares/middlewares';
```

2021-08-12 16:45 UTC, Sayonarko commented on frontend/src/middlewares/socket/socket.middleware.ts
> +const socketMiddleware: Middleware = ({ dispatch }) => (next): Next => {
Yep. Without this type checks failed

2021-08-13 08:39 UTC, ZubkoWhatislove approved these changes

2021-08-13 08:45 UTC, merged