J111 notifications page
BinaryStudioAcademy/bsa-2021-jabber pull request #139
Opened 2021-08-12 08:29 UTC by EugeniusGR

![image](https://user-images.githubusercontent.com/35200697/129164564-6b85930e-3fd1-4c1b-89ff-db594e66b61b.png)

and read notification:
![image](https://user-images.githubusercontent.com/35200697/129164629-ac45b5a8-3ae0-482f-bf67-932c2ec19ddc.png)

2021-08-12 09:10 UTC, ZubkoWhatislove requested changes
![image](https://user-images.githubusercontent.com/60396171/129170628-177e8066-2a06-4ee4-8218-fd1f1d96074a.png)
use our common checkbox component, and use our primary color for the eye icon & see messages button

2021-08-12 09:10 UTC, ZubkoWhatislove commented on frontend/src/components/common/header/header.tsx
> +                </button>
```suggestion
                  <img src={headerBell} width="23" height="23" loading="lazy" alt="" />
```

2021-08-12 09:10 UTC, ZubkoWhatislove commented on frontend/src/components/common/header/styles.module.scss
> +  cursor: pointer;
```suggestion
```

2021-08-12 09:10 UTC, ZubkoWhatislove commented on frontend/src/components/notifications/components/notification-item.tsx
> +import defaultLogo from 'assets/img/default-notifications.png';
```suggestion
import notification-icon from 'assets/img/notification-icon.png';
```

2021-08-12 09:10 UTC, ZubkoWhatislove commented on frontend/src/components/notifications/components/styles.module.scss
> +  @extend .container;
```suggestion
  .container;
```
don't use extend

2021-08-12 11:11 UTC, ZubkoWhatislove requested changes

2021-08-12 11:11 UTC, ZubkoWhatislove commented on frontend/src/components/common/header/header.tsx
> +                  height="23"
```suggestion
                  width="23"
                  height="23"
                  loading="lazy"
                  alt=""
```

2021-08-12 11:11 UTC, ZubkoWhatislove commented on frontend/src/components/notifications/components/notification-item.tsx
> +    <div className={styles.container}>
```suggestion
    <li className={styles.container}>
```

2021-08-12 11:11 UTC, ZubkoWhatislove commented on frontend/src/components/notifications/notifications.tsx
> +    </div>
```suggestion
       <ul className={styles.container}>
         <NotificationItem />
        </ul>
```

2021-08-12 12:43 UTC, ZubkoWhatislove requested changes

2021-08-12 12:43 UTC, ZubkoWhatislove commented on frontend/src/components/common/header/header.tsx
> +                  alt="notifications"
```suggestion
                  alt=""
```

2021-08-12 12:43 UTC, ZubkoWhatislove commented on frontend/src/components/notifications/notifications.tsx
> +    </li>
```suggestion
    <ul className={styles.container}>
      <NotificationItem />
    </ul>
```

2021-08-12 12:43 UTC, ZubkoWhatislove commented on frontend/src/components/notifications/components/notification-item.tsx
> +    </ul>
```suggestion
    <li className={styles.container}>
      <div className={styles.notificationLogo}>
        <img
          className={styles.image}
          src={notificationIcon}
          width="40"
          height="40"
        />
      </div>
      <div className={styles.notificationInfo}>
        <h2 className={styles.infoTitle}>
          You have a new message from Lincoln
        </h2>
        <p className={styles.notificationText}>
          Four score and seven years ago our fathers brought forth, on this
          continent, a new nation, conceived in Liberty, and dedicated to the
          proposition that all men are created equal. Now we are engaged in a
          great civil war, testing whether that nation, or any nation so
          conceived, and so dedicated, can long endure.
        </p>
        <Link to={AppRoute.NOTIFICATIONS} className={styles.link}>
          See message
        </Link>
      </div>
      <div className={styles.notificationStatus}>
        <button className={styles.buttonEye}>
          <img src={newNotificationEye} width="25" height="25" />
        </button>
        <span className={styles.notificationDate}>09:31</span>
      </div>
    </li>
```

2021-08-12 12:45 UTC, ZubkoWhatislove reviewed
add `notifications` reducer

2021-08-12 12:46 UTC, ZubkoWhatislove requested changes

2021-08-12 12:46 UTC, ZubkoWhatislove commented on frontend/src/components/notifications/notifications.tsx
> +};
```suggestion
const Notifications: React.FC = () => {
  const { notifications } = useSelector(({ notifications }) => ({
    notifications: notifications.notifications
  }));
  return (
    <li className={styles.container}>
    {notifications.map((it) => (
           <NotificationItem notification={it} key={it.id} />
    ))}
    </li>
  );
};
```

2021-08-13 09:14 UTC, JuliaDzyuba submitted a review, later dismissed

2021-08-13 12:10 UTC, EugeniusGR commented
I created just mocked reducer coz I have troubles with backend part

2021-08-13 15:43 UTC, ZubkoWhatislove requested changes

2021-08-13 15:43 UTC, ZubkoWhatislove commented on frontend/src/store/notification/reducer.ts
> +  notifications: UserNotification[] | UserNotification | null;
```suggestion
  notifications: UserNotification[];
```

2021-08-13 15:43 UTC, ZubkoWhatislove commented on frontend/src/store/notification/common.ts
> +  LOAD_USER = 'user-profile/load-user',
```suggestion
```

2021-08-13 15:43 UTC, ZubkoWhatislove commented on frontend/src/store/notification/actions.ts
> +    return user;
something wrong

2021-08-14 05:55 UTC, ZubkoWhatislove requested changes

2021-08-14 05:55 UTC, ZubkoWhatislove commented on shared/src/common/types/notification/notifications.type.ts
> +type Notifications = {
```suggestion
type Notification = {
```

2021-08-14 05:55 UTC, ZubkoWhatislove commented on shared/src/common/types/notification/notifications.type.ts
> +type Notifications = {
don't forget to rename file

2021-08-14 05:55 UTC, ZubkoWhatislove commented on shared/src/common/enums/api/notification-api-path.enum.ts
> +declare enum NotificationApiPath {
```suggestion
 enum NotificationsApiPath {
```

2021-08-14 05:55 UTC, ZubkoWhatislove commented on shared/src/common/enums/api/notification-api-path.enum.ts
> +declare enum NotificationApiPath {
don't forget about filename

2021-08-14 05:55 UTC, ZubkoWhatislove commented on shared/src/common/types/user-notification/user-notification.type.ts
> +  notifications : Notifications;
```suggestion
  notifications : Notification[];
```

2021-08-14 05:55 UTC, ZubkoWhatislove commented on shared/src/common/types/user-notification/user-notification.type.ts
> +import { Notifications } from 'src/common/types/notification/notifications.type';
```suggestion
import { Notifications } from '~/common/types/notification/notifications.type';
```

2021-08-14 05:55 UTC, ZubkoWhatislove commented on frontend/src/components/notifications/components/notification-item.tsx
> +          <img src={newNotificationEye} width="25" height="25" />
add this image as background image

2021-08-14 07:13 UTC, yevhenprybytok approved these changes, later dismissed

2021-08-14 09:10 UTC, EugeniusGR commented
![](https://github.trello.services/images/mini-trello-icon.png) [Notifications page](https://trello.com/c/Rrz6mZbX/111-notifications-page)

2021-08-14 17:55 UTC, what1s1ove requested changes

2021-08-14 17:55 UTC, what1s1ove commented on frontend/src/components/notifications/notifications.tsx
> +        <NotificationItem notification={notification} />;
add key

2021-08-15 05:47 UTC, what1s1ove approved these changes

2021-08-15 05:53 UTC, merged