Task as/j135 select cover podcast image functionality
BinaryStudioAcademy/bsa-2021-jabber pull request #158
Opened 2021-08-13 14:23 UTC by qwiz1

![2021-08-13 16_17_23-Jabber](https://user-images.githubusercontent.com/22223694/129371763-212c6f74-6b71-481c-baca-73c9ab6d4f8f.png)
![2021-08-13 16_18_56-Jabber](https://user-images.githubusercontent.com/22223694/129371767-ff5e15a6-050d-433d-bc3c-de1dabb4178e.png)

2021-08-14 05:45 UTC, ZubkoWhatislove approved these changes, later dismissed

2021-08-14 06:52 UTC, JuliaDzyuba submitted a review, later dismissed

2021-08-14 12:50 UTC, artem-totality submitted a review, later dismissed

2021-08-14 17:42 UTC, what1s1ove requested changes

2021-08-14 17:42 UTC, what1s1ove commented on frontend/src/common/enums/ui/image-preview-control-style.enum.ts
> +enum ImagePreviewStyle {
remove it

2021-08-14 17:42 UTC, what1s1ove commented on frontend/src/components/common/image-preview-control/image-preview-control.tsx
> +  imagePreviewStyle?: ImagePreviewStyle;
```suggestion
```

2021-08-14 17:42 UTC, what1s1ove commented on frontend/src/components/common/image-preview-control/image-preview-control.tsx
> +  imagePreviewStyle?: ImagePreviewStyle;
you className to give styles for this block

2021-08-14 17:42 UTC, what1s1ove commented on frontend/src/components/common/image-preview-control/image-preview-control.tsx
> +        </div>
```suggestion
        {label && 
        <span className={styles.cornerRight}>
          {label}
        </span>}
```

2021-08-15 08:05 UTC, what1s1ove requested changes

2021-08-15 08:05 UTC, what1s1ove commented on frontend/src/components/configurate-podcast/components/configurate-podcast-form/styles.module.scss
> +    max-width: 358px;
```suggestion
    max-width: 358px;
    margin: 0 auto;
```

2021-08-15 09:06 UTC, what1s1ove approved these changes

2021-08-15 09:08 UTC, merged