Task dl/j143 edit user functionality
BinaryStudioAcademy/bsa-2021-jabber pull request #166
Opened 2021-08-14 15:47 UTC by Denidzio

![Screenshot from 2021-08-14 18-46-16](https://user-images.githubusercontent.com/60543500/129451772-2fa82c0b-4866-429a-8aac-a02a56af7cc8.png)

2021-08-14 17:46 UTC, what1s1ove requested changes
remove the password from form and add the `bio` field
don't forget to fix import

2021-08-14 17:46 UTC, what1s1ove commented on backend/src/services/user/user.service.ts
> +    if (userWithSimilarEmail && userWithSimilarEmail.id !== id) {
```suggestion
    if (userWithSimilarEmail?.id !== id) {
```

2021-08-15 07:33 UTC, Denidzio commented
![Screenshot from 2021-08-15 10-31-59](https://user-images.githubusercontent.com/60543500/129470758-31c41a5e-6211-40c1-981c-095c135155a5.png)

2021-08-15 11:28 UTC, what1s1ove requested changes

2021-08-15 11:28 UTC, what1s1ove commented on backend/src/services/user/user.service.ts
> +      updatedUser.password = user.password;
but we can't change it in the payload for editing 🤔

2021-08-15 11:28 UTC, what1s1ove commented on frontend/src/common/types/user/user-form-payload.type.ts
> +};
🤔
```suggestion
type UserFormPayload = UserEditPayload & {
  [UserPayloadKey.BIRTHDATE]: Date;
};
```

2021-08-15 11:28 UTC, what1s1ove commented on frontend/src/store/user-profile/actions.ts
> +const updateUser = createAsyncThunk<User, UserEditPayload, AsyncThunkConfig>(
you need to create your own reducer `configurate-user`

2021-08-15 11:28 UTC, what1s1ove commented on frontend/src/store/user-profile/reducer.ts
> +  builder.addCase(updateUser.pending, (state) => {
you need to create your own reducer for it

2021-08-15 11:28 UTC, what1s1ove commented on frontend/src/store/user-profile/common.ts
> +  UPDATE_USER = 'user-profile/update-user',
```suggestion
```

2021-08-15 11:28 UTC, what1s1ove commented on shared/src/common/types/user/user-edit-payload.type.ts
> +  [UserPayloadKey.PASSWORD]?: string;
```suggestion
```

2021-08-15 16:37 UTC, what1s1ove requested changes

2021-08-15 16:37 UTC, what1s1ove commented on frontend/src/store/configurate-user/actions.ts
> +
add redirect

2021-08-15 16:37 UTC, what1s1ove commented on frontend/src/store/root-reducer.ts
> +  configurateUser,
```suggestion
  notification,
    configurateUser,
  toastr: toastrReducer,
```

2021-08-16 05:08 UTC, what1s1ove submitted a review, later dismissed

2021-08-16 06:26 UTC, what1s1ove approved these changes

2021-08-16 06:27 UTC, merged