Task sf/j22 add handleerror middleware
BinaryStudioAcademy/bsa-2021-jabber pull request #17
Opened 2021-07-28 13:58 UTC by Sayonarko

2021-07-28 13:59 UTC, Sayonarko commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create `handleError` middleware for redux](https://trello.com/c/LCyAGqxd/22-create-handleerror-middleware-for-redux)

2021-07-28 14:01 UTC, ZubkoWhatislove requested changes
Very good!

Also, check check status in the http service a bit:

```
  private async checkStatus(response: Response): Promise<Response> {
    if (!response.ok) {
      const parsedException = await response.json().catch(() => ({
        message: response.statusText,
      }));

      throw new HttpError({
        status: response.status,
        message: parsedException?.message,
      });
    }
```

2021-07-28 14:01 UTC, ghost commented on frontend/src/middlewares/middlewares.ts
> +export * from './handle-error/handle-error.middleware';
```suggestion
export { handleError } from './handle-error/handle-error.middleware';
```

2021-07-28 14:01 UTC, ghost commented on frontend/src/middlewares/handle-error/handle-error.middleware.ts
> +  next(action);
```suggestion
  const hasErrorMessage = Boolean(action?.error?.message);
  
  if (hasErrorMessage) {
    notificationService.error('Error', action.payload.error.message);
  }
  
  next(action);
```
awesome!

2021-07-28 14:45 UTC, ZubkoWhatislove approved these changes
LGTM 👍

2021-07-28 23:15 UTC, Liza-Veis approved these changes

2021-07-29 06:59 UTC, yevhenprybytok approved these changes

2021-07-29 07:17 UTC, merged