J170: + type for episode
BinaryStudioAcademy/bsa-2021-jabber pull request #176
Opened 2021-08-15 13:33 UTC by EugeniusGR

![image](https://user-images.githubusercontent.com/35200697/129480323-79692e27-9819-462d-89b5-70fa94b44ede.png)

2021-08-15 13:37 UTC, what1s1ove requested changes

2021-08-15 13:37 UTC, what1s1ove commented on frontend/src/components/episode/episode.tsx
> +                <p className={styles.episodeInfo}>Status: {episode.status}</p>
```suggestion
<dl>
    <dt>Type: </dt>
    <dd>{episode.type}</dd>
    <dt>Status:</dt>
    <dd>{episode.status}</dd>
</dl>
```

2021-08-15 16:02 UTC, what1s1ove requested changes

2021-08-15 16:02 UTC, what1s1ove commented on frontend/src/components/episode/styles.module.scss
> +}
```suggestion
```

2021-08-15 16:02 UTC, what1s1ove commented on frontend/src/components/episode/styles.module.scss
>  }
```suggestion
```
you don't use it, right?

2021-08-15 16:02 UTC, what1s1ove commented on frontend/src/components/episode/episode.tsx
> +                </dl>
```suggestion
                <dl>
                   <div>
                                     <dt>Type: </dt>
                  <dd>{episode.type}</dd>
                   </div>
                   <div>
                                     <dt>Status:</dt>
                  <dd>{episode.status}</dd>
                   </div>
                </dl>
```
add style by classes

2021-08-16 05:08 UTC, what1s1ove requested changes

2021-08-16 05:08 UTC, what1s1ove commented on frontend/src/components/episode/styles.module.scss
> +  }
we don't use the float for layout
use `display: flex`;

2021-08-16 07:26 UTC, EugeniusGR commented
![image](https://user-images.githubusercontent.com/35200697/129526554-3ce1b4e2-6c98-4b8e-93eb-8df5737ae00e.png)

2021-08-16 07:44 UTC, what1s1ove approved these changes

2021-08-16 07:44 UTC, merged