Task jd/j160 add genre info to podcast page
BinaryStudioAcademy/bsa-2021-jabber pull request #177
Opened 2021-08-15 16:22 UTC by JuliaDzyuba

![151921](https://user-images.githubusercontent.com/60258687/129485257-f4644311-c5a4-446a-b352-fd81419b1b93.png)

2021-08-15 16:25 UTC, what1s1ove requested changes

2021-08-15 16:25 UTC, what1s1ove commented on backend/src/data/models/podcast/podcast.model.ts
> +import { Genre } from '../genre/genre.model';
```suggestion
import { Genre } from '~data/models/genre/genre.model';
```

2021-08-15 16:25 UTC, what1s1ove commented on backend/src/data/models/podcast/podcast.model.ts
> +  [PodcastDTOKey.GENRE]: Genre;
```suggestion
  [PodcastDTOKey.GENRE]: Genre | null;
```

2021-08-15 16:25 UTC, what1s1ove commented on frontend/src/components/podcast/podcast.tsx
> +                  <div className={`${styles.infoName} ${styles.genre}`}>Genre</div>
```suggestion
                  <div className={getValidClasses(styles.infoName, styles.genre)}>Genre</div>
```

2021-08-15 16:25 UTC, what1s1ove commented on shared/src/common/types/podcast/podcast.type.ts
> +  genre: Genre;
```suggestion
  genre: Genre | null;
```

2021-08-15 18:36 UTC, Denidzio submitted a review, later dismissed

2021-08-16 05:03 UTC, what1s1ove requested changes

2021-08-16 05:03 UTC, what1s1ove commented on frontend/src/components/podcast/podcast.tsx
> +import { getAllowedClasses } from 'helpers/dom/dom';
```suggestion
import { getAllowedClasses } from 'helpers/helpers';
```
keep import order

2021-08-16 06:02 UTC, what1s1ove requested changes

2021-08-16 06:02 UTC, what1s1ove commented on frontend/src/components/common/image-preview-control/image-preview-control.tsx
> +// import { getAllowedClasses } from 'helpers/dom/dom';
```suggestion
```

2021-08-16 06:12 UTC, what1s1ove approved these changes

2021-08-16 06:15 UTC, merged