Task av/j168 add comments timelines near the audio
BinaryStudioAcademy/bsa-2021-jabber pull request #196
Opened 2021-08-16 19:15 UTC by artem-totality

2021-08-17 05:57 UTC, what1s1ove requested changes

2021-08-17 05:57 UTC, what1s1ove commented on frontend/src/components/episode/components/timeline-item/timeline-item.tsx
> +    100;
move this calculation to the function `frontend/src/components/episode/components/timeline-item/helpers`

2021-08-17 05:57 UTC, what1s1ove commented on frontend/src/components/common/player/player.tsx
> +import { DataStatus } from 'common/enums/enums';
keep import order

2021-08-17 05:57 UTC, what1s1ove commented on frontend/src/components/common/player/player.tsx
> +          dispatch(playerActions.setPlayerStatus(DataStatus.PENDING));
remove anonymous functions from the `jsx`

2021-08-17 05:57 UTC, what1s1ove commented on frontend/src/components/episode/components/comments-timeline/comments-timeline.tsx
> +          {...props}
avoid it

2021-08-17 05:57 UTC, what1s1ove commented on frontend/src/components/episode/components/comments-timeline/comments-timeline.tsx
> +          handleGoToTimestamp={(): void => {
check the **A9** criteria
Remove anonymous functions from the jsx

2021-08-17 05:57 UTC, what1s1ove commented on frontend/src/components/episode/components/timeline-item/timeline-item.tsx
> +      onClick={handleGoToTimestamp}
don't use `onClick` on `div`. Use `button` instead

2021-08-17 05:57 UTC, what1s1ove commented on frontend/src/components/episode/episode.tsx
> +
```suggestion
```

2021-08-17 08:21 UTC, JuliaDzyuba submitted a review, later dismissed

2021-08-17 12:10 UTC, what1s1ove requested changes

2021-08-17 12:10 UTC, what1s1ove commented on frontend/src/components/common/player/player.tsx
> +  setPlayerStatus: React.Dispatch<React.SetStateAction<DataStatus>>;
check **A9** criteria

2021-08-17 12:10 UTC, what1s1ove commented on frontend/src/components/episode/components/comments-timeline/comments-timeline.tsx
> +  playerContainerRef,
```suggestion
```
This component shouldn't know anything about player ref

2021-08-17 12:16 UTC, yevhenprybytok approved these changes, later dismissed

2021-08-17 14:46 UTC, what1s1ove requested changes

2021-08-17 14:46 UTC, what1s1ove commented on frontend/src/components/common/player/player.tsx
> +  handleSetPlayerStatus: React.Dispatch<React.SetStateAction<DataStatus>>;
Check **A8** criteria

2021-08-17 14:46 UTC, what1s1ove commented on frontend/src/components/common/player/player.tsx
> +        if (playerRef.current && playerRef.current.audio.current) {
```suggestion
        if (playerRef.current?.audio.current) {
```

2021-08-17 14:46 UTC, what1s1ove commented on frontend/src/components/episode/components/timeline-item/timeline-item.tsx
> +      onClick={handleGoToItemTimestamp(comment.timestamp)}
remove anonymous functions from jsx

2021-08-17 14:46 UTC, what1s1ove commented on frontend/src/components/episode/components/timeline-item/timeline-item.tsx
> +    <button
```suggestion
    <li>
     <button className={styles.timelineItem}>
     //
     </li>
```

2021-08-17 14:46 UTC, what1s1ove commented on frontend/src/components/episode/helpers/get-comments-timeline-dimensions/get-comments-timeline-dimensions.helper.ts
> +  return dimensions;
```suggestion
  return {
    offset,
    progressBarWidth,
    playerContainerWidth,
  };
```

2021-08-17 18:09 UTC, what1s1ove requested changes

2021-08-17 18:09 UTC, what1s1ove commented on frontend/src/components/common/player/player.tsx
> +  handleSetPlayerStatus: React.Dispatch<React.SetStateAction<DataStatus>>;
don't fixed

2021-08-18 05:31 UTC, what1s1ove approved these changes

2021-08-18 05:31 UTC, merged