J-181: added sorting genres options
BinaryStudioAcademy/bsa-2021-jabber pull request #203
Opened 2021-08-17 11:56 UTC by JuliaDzyuba

![171415](https://user-images.githubusercontent.com/60258687/129721361-a93bebb1-8250-43eb-a84f-b8c0dac4e3b3.png)

2021-08-17 12:02 UTC, what1s1ove requested changes

2021-08-17 12:02 UTC, what1s1ove commented on frontend/src/components/configurate-podcast/components/configurate-podcast-form/configurate-podcast-form.tsx
> +  const sortedGenres = genres.sort((a, b) => a.label > b.label ? 1 : -1);
sort mutates an array
firstly we need to copy this array

2021-08-17 12:03 UTC, yevhenprybytok commented on frontend/src/components/configurate-podcast/components/configurate-podcast-form/configurate-podcast-form.tsx
> +  const sortedGenres = genres.sort((a, b) => a.label > b.label ? 1 : -1);
Do we sort it by the length of the word?

2021-08-17 12:05 UTC, Denidzio commented on frontend/src/components/configurate-podcast/components/configurate-podcast-form/configurate-podcast-form.tsx
> +  const sortedGenres = genres.sort((a, b) => a.label > b.label ? 1 : -1);
Does `label` field has string type? JavaScript `.sort` sorts strings by default and we can remove `(a, b) => a.label > b.label ? 1 : -1` .

2021-08-17 14:39 UTC, what1s1ove requested changes

2021-08-17 14:39 UTC, what1s1ove commented on frontend/src/components/configurate-podcast/components/configurate-podcast-form/configurate-podcast-form.tsx
> +  const sortedGenres = [...genres].sort((a, b) => a.label > b.label ? 1 : -1);
you need to create a function from it and move it to `frontend/src/components/configurate-podcast/components/configurate-podcast-form/helpers`

2021-08-18 05:00 UTC, what1s1ove requested changes

2021-08-18 05:00 UTC, what1s1ove commented on frontend/src/components/configurate-podcast/helpers/sort-genres-by-name/sort-genres-by-name.ts
> +  return [...options].sort((a, b) => a.label > b.label ? 1 : -1);
```suggestion
  return [...options].sort((a, b) => a.label.localeCompare(b.label));
```

2021-08-18 06:08 UTC, what1s1ove approved these changes

2021-08-18 06:13 UTC, merged