Task ys/j179 add sort for the episode table
BinaryStudioAcademy/bsa-2021-jabber pull request #205
Opened 2021-08-17 13:58 UTC by yaroslav207

2021-08-17 14:05 UTC, what1s1ove requested changes

2021-08-17 14:05 UTC, what1s1ove commented on frontend/src/components/common/table/table.tsx
> +                      : (<img src={arrowUp} className={styles.sortArrow} alt="sort-desc" />)
do it with classes & background image

2021-08-17 18:06 UTC, what1s1ove requested changes

2021-08-17 18:06 UTC, what1s1ove commented on frontend/src/components/common/table/table.tsx
> +                <span className={`${styles.sortIndicator} ${column.isSorted
use `getAllowedClasses` for more than 1 class

2021-08-18 03:03 UTC, JuliaDzyuba approved these changes

2021-08-18 04:58 UTC, what1s1ove approved these changes

2021-08-18 04:59 UTC, merged