Task vv/19 Added modal component
BinaryStudioAcademy/bsa-2021-jabber pull request #206
Opened 2021-08-17 14:06 UTC by vitalik-prog

2021-08-17 14:13 UTC, what1s1ove requested changes
frontend/package-lock.json shouldn't be changed so much

2021-08-17 14:13 UTC, what1s1ove commented on frontend/src/components/common/modal/modal.tsx
> +      <button className={styles.closeBtn} onClick={handleCloseModal}> X </button>
```suggestion
```

2021-08-17 14:13 UTC, what1s1ove commented on frontend/src/components/common/modal/modal.tsx
> +      shouldCloseOnOverlayClick={true}
```suggestion
      shouldCloseOnOverlayClick
```

2021-08-17 14:13 UTC, what1s1ove commented on frontend/src/components/common/modal/modal.tsx
> +  showModal: boolean;
```suggestion
  isShowModal: boolean;
```

2021-08-17 14:13 UTC, what1s1ove commented on frontend/src/components/common/modal/modal.tsx
> +  children: React.ReactNode;
```suggestion
```

2021-08-17 14:13 UTC, what1s1ove commented on frontend/package.json
> +    "@types/react-modal": "^3.12.1",
check **B17**

2021-08-17 14:13 UTC, what1s1ove commented on frontend/src/components/common/modal/modal.tsx
> +  handleCloseModal?: () => void;
check **A8**

2021-08-17 14:13 UTC, what1s1ove commented on package-lock.json
> -{
it should be changed

2021-08-17 18:05 UTC, what1s1ove requested changes

2021-08-17 18:05 UTC, what1s1ove commented on frontend/package.json
> +    "@types/react-modal": "3.12.1",
types should be in the `devDependencies`

2021-08-17 18:05 UTC, what1s1ove commented on package-lock.json
> -{
don't fixed

2021-08-18 02:58 UTC, JuliaDzyuba approved these changes, later dismissed

2021-08-18 04:58 UTC, what1s1ove requested changes

2021-08-18 04:58 UTC, what1s1ove commented on package-lock.json
> -{
don't fixed

2021-08-18 05:18 UTC, what1s1ove approved these changes

2021-08-18 05:21 UTC, merged