J-202: *styles-for-auth-adaptive
BinaryStudioAcademy/bsa-2021-jabber pull request #243
Opened 2021-08-20 09:36 UTC by EugeniusGR

![image](https://user-images.githubusercontent.com/35200697/130213473-49af51df-f104-4608-8b9f-813b4d46c900.png)

2021-08-20 09:43 UTC, Denidzio commented
I think it's too narrow for fields

2021-08-20 09:46 UTC, Denidzio requested changes

2021-08-20 09:46 UTC, Denidzio commented on frontend/src/components/auth/styles.module.scss
> +    padding: 50px;
```suggestion
    padding: 20px;
```

2021-08-20 09:46 UTC, Denidzio commented on frontend/src/components/auth/styles.module.scss
> +    margin-bottom: 0;
Why did you repeat the basic styles?

2021-08-20 09:48 UTC, EugeniusGR commented on frontend/src/components/auth/styles.module.scss
> +    margin-bottom: 0;
oh, forgot to delete

2021-08-20 10:00 UTC, Denidzio commented on frontend/src/components/auth/styles.module.scss
> +  width: 480px;
```suggestion
  max-width: 480px;
  width: 100%;
```

2021-08-20 10:00 UTC, Denidzio commented on frontend/src/components/auth/styles.module.scss
> +    width: 100%;
```suggestion
```
I think if our form is 100% width at 550 pixels, it won't be very pretty. Better to constrain the form to the standard 480 pixels, and it will shrink as the screen shrinks.

2021-08-20 10:20 UTC, EugeniusGR commented on frontend/src/components/auth/styles.module.scss
> +    width: 100%;
If I convert it to pixels it will be less adaptive

2021-08-20 10:26 UTC, Denidzio commented on frontend/src/components/auth/styles.module.scss
> +    width: 100%;
Maybe, it's hard to predict for me. We don't have a layout for it. Therefore, we can design it in different ways.

2021-08-21 04:38 UTC, what1s1ove requested changes

2021-08-21 04:38 UTC, what1s1ove commented on frontend/src/components/auth/styles.module.scss
> +  width: 480px;
agreed!

2021-08-22 06:49 UTC, what1s1ove requested changes
we should have a max-width, not a min-width

2021-08-22 08:34 UTC, what1s1ove approved these changes

2021-08-22 09:52 UTC, merged