Task yc/j222 add library for popuper to handle screen overlapping
BinaryStudioAcademy/bsa-2021-jabber pull request #245
Opened 2021-08-20 12:27 UTC by EugeniusGR

![image](https://user-images.githubusercontent.com/35200697/130232970-cb61581d-1619-4aa8-9ef8-0329d7b4b4bb.png)

2021-08-21 04:39 UTC, what1s1ove requested changes

2021-08-21 04:39 UTC, what1s1ove commented on frontend/src/components/common/header/header.tsx
> +import Popup from 'reactjs-popup';
we can't import it directly
we need to wrap it in the `common` components folder

2021-08-21 11:16 UTC, JuliaDzyuba submitted a review, later dismissed

2021-08-22 06:50 UTC, what1s1ove requested changes
Check the modal component, and do something like this

2021-08-23 15:38 UTC, what1s1ove requested changes

2021-08-23 15:38 UTC, what1s1ove commented on frontend/src/components/common/common.ts
> +export { default as PopUp } from './popuper/popuper';
```suggestion
export { default as Popuper } from './popuper/popuper';
```

2021-08-23 15:38 UTC, what1s1ove commented on frontend/src/components/common/header/popus.styles.scss
> +}
```suggestion
```
move it to `frontend/src/components/common/header/styles.module.scss`
just use `global` selector

2021-08-23 18:28 UTC, what1s1ove approved these changes

2021-08-23 18:30 UTC, merged