Task av/j89 add filter functionality
BinaryStudioAcademy/bsa-2021-jabber pull request #249
Opened 2021-08-20 16:31 UTC by artem-totality

2021-08-21 04:45 UTC, what1s1ove requested changes

2021-08-21 04:45 UTC, what1s1ove commented on frontend/src/store/root-reducer.ts
> +import { reducer as genre } from './genre/reducer';
```suggestion
```
you need to load gender in the homepage reducer

2021-08-21 04:45 UTC, what1s1ove commented on frontend/src/components/configurate-podcast/configurate-podcast.tsx
> -    dispatch(configuratePodcastActions.loadGenres());
why did you remove it?
what if the user go directly to this page?

2021-08-21 04:45 UTC, what1s1ove commented on frontend/src/components/common/podcast-filter/podcast-filter.tsx
> +            </button>
I removed it from the design

2021-08-21 04:45 UTC, what1s1ove commented on frontend/src/common/types/http/http-options.type.ts
> +  query: Record<string, any>;
```suggestion
  query: Record<string, unknown>;
```

2021-08-21 04:45 UTC, what1s1ove commented on backend/src/data/models/podcast/podcast.model.ts
> +class PodcastQueryBuilder<M extends Model, R = M[]> extends QueryBuilder<M, R> {
move it to `backend/src/data/models/podcast/common/`

2021-08-21 04:45 UTC, what1s1ove commented on frontend/src/components/app/app.tsx
> +    dispatch(genreActions.loadGenres());
```suggestion
```

2021-08-21 04:45 UTC, what1s1ove commented on frontend/src/components/app/app.tsx
> +import { auth as authActions, genre as genreActions } from 'store/actions';
```suggestion
import { auth as authActions } from 'store/actions';
```

2021-08-21 07:14 UTC, what1s1ove requested changes

2021-08-21 07:14 UTC, what1s1ove commented on backend/src/data/models/podcast/common/podcast-query-builder.ts
> +import { Model, Page, QueryBuilder } from 'objection';
backend/src/data/models/podcast/common/query-builder/query-builder.ts

2021-08-21 07:14 UTC, what1s1ove commented on backend/src/data/models/podcast/common/podcast-query-builder.ts
> +class PodcastQueryBuilder<M extends Model, R = M[]> extends QueryBuilder<M, R> {
```suggestion
class QueryBuilder<M extends Model, R = M[]> extends QueryBuilder<M, R> {
```

2021-08-21 07:14 UTC, what1s1ove commented on frontend/src/components/common/podcast-filter/podcast-filter.tsx
> +import { Path, FieldValues } from 'react-hook-form';
this component should be as popup
logic for opening/closing should be in the homapage component

2021-08-21 07:14 UTC, what1s1ove commented on frontend/src/components/common/podcast-filter/podcast-filter.tsx
> +                      name={`genresFilter.${index}` as Path<FieldValues>}
```suggestion
                      name={`genresFilter.${genre.key}` as Path<FieldValues>}
```
we should use `key` for manipulating and avoid indexes

2021-08-21 13:53 UTC, JuliaDzyuba submitted a review, later dismissed

2021-08-22 14:03 UTC, what1s1ove requested changes

2021-08-22 14:03 UTC, what1s1ove commented on frontend/src/components/homepage/homepage.tsx
> +            )}
move it at the bottom of the component

2021-08-22 14:03 UTC, what1s1ove commented on frontend/src/components/homepage/homepage.tsx
> +              onClick={(): void => setIsFilterVisible(!isFilterVisible)}
avoid anonymous functions in jsx

2021-08-22 14:03 UTC, what1s1ove commented on frontend/src/components/common/podcast-filter/podcast-filter.tsx
> +  }, {});
```suggestion
  const currentValues = genres.reduce<Record<string, boolean>>((acc, genre) => {
    return {
      ...acc,
      [genre.key] = currentState.genres.includes(genre.id);
    };
  }, {});
```
create a helper from it and move to frontend/src/components/common/podcast-filter/helpers/

2021-08-22 14:03 UTC, what1s1ove commented on frontend/src/components/homepage/homepage.tsx
> +    }, []);
```suggestion
    const selectedGenres = genres.reduce<number[]>((acc, genre) => {
    const hasGender = Boolean(genresFilter[genre.key]);
      return hasGender ? acc.concat(genre.id) ? acc;
    }, []);
```
create a helper from it and move to frontend/src/components/homepage/helpers

2021-08-23 09:42 UTC, what1s1ove requested changes

2021-08-23 09:42 UTC, what1s1ove commented on frontend/src/components/common/podcast-filter/helpers/get-current-values.helper/get-current-values.helper.ts
> +import { Genre, PodcastLoadFilter } from 'common/types/types';
move it to `frontend/src/components/common/podcast-filter/helpers/get-current-values/get-current-values.helper.ts`

2021-08-23 10:11 UTC, what1s1ove approved these changes

2021-08-23 10:11 UTC, merged