task-sf/J240-bugfix-live-page-buttons
BinaryStudioAcademy/bsa-2021-jabber pull request #254
Opened 2021-08-21 15:20 UTC by Sayonarko

![live](https://user-images.githubusercontent.com/35679428/130326469-cfc63232-d0a7-441f-829a-b6cd3f979b7e.png)

2021-08-21 16:01 UTC, Denidzio submitted a review, later dismissed

2021-08-21 16:11 UTC, what1s1ove requested changes

2021-08-21 16:11 UTC, what1s1ove commented on frontend/src/components/episode-live/episode-live.tsx
> +import { ReactComponent as RecordIcon } from 'assets/img/player/record.svg';
add them as background and just change the opacity on the button while hovering

2021-08-22 06:38 UTC, what1s1ove approved these changes
LGTM 👍

2021-08-22 06:41 UTC, merged