Task av/j34 create podcast page
BinaryStudioAcademy/bsa-2021-jabber pull request #26
Opened 2021-07-29 19:16 UTC by artem-totality

2021-07-30 04:32 UTC, ZubkoWhatislove requested changes

2021-07-30 04:32 UTC, ZubkoWhatislove commented on frontend/src/components/common/button/button.tsx
> +import React from 'react';
```suggestion
```

2021-07-30 04:32 UTC, ZubkoWhatislove commented on frontend/src/components/create-podcast/create-podcast.tsx
> +    useState<PodcastCreatePayload>({
```suggestion
    useState<PodcastCreatePayload>({
```
use useForm hook for all forms

2021-07-30 04:32 UTC, ZubkoWhatislove commented on frontend/src/services/podcast-api/podcast-api.service.ts
> +  public postPodcast(payload: PodcastCreatePayload): Promise<Podcast> {
```suggestion
  public create(payload: PodcastCreatePayload): Promise<Podcast> {
```

2021-07-30 04:32 UTC, ZubkoWhatislove commented on frontend/src/store/podcast/actions.ts
> +// prettier-ignore
```suggestion
```

2021-07-30 04:32 UTC, ZubkoWhatislove commented on frontend/src/store/podcast/reducer.ts
> +import { createReducer } from '@reduxjs/toolkit';
your page is responsible for creating or editing a podcast. Therefore, the reducer and actions should be called `configurate-pocast`

2021-07-30 04:32 UTC, ZubkoWhatislove commented on frontend/src/store/root-reducer.ts
> +import { reducer as podcast } from './podcast/reducer';
```suggestion
import { reducer as configuratePodcast } from './podcast/reducer';
```

2021-07-30 04:32 UTC, ZubkoWhatislove commented on frontend/src/components/common/button/button.tsx
> +  },
```suggestion
  onClick
```

2021-07-30 04:32 UTC, ZubkoWhatislove requested changes
don't forget to add this page to app routing

2021-07-30 07:20 UTC, yevhenprybytok requested changes

2021-07-30 07:20 UTC, yevhenprybytok commented on frontend/src/components/create-podcast/create-podcast.tsx
> +  const isFormDisable = createPodcastStatus === DataStatus.PENDING;
```suggestion
  const isFormDisabled = createPodcastStatus === DataStatus.PENDING;
```

2021-07-30 07:20 UTC, yevhenprybytok commented on frontend/src/components/create-podcast/create-podcast.tsx
> +                value={''}
```suggestion
                value=""
```

2021-07-30 07:20 UTC, yevhenprybytok commented on frontend/src/components/create-podcast/create-podcast.tsx
> +            <img src={'https://via.placeholder.com/150'} />
Fallback images should be located in assets directory

2021-07-30 14:56 UTC, ZubkoWhatislove requested changes

2021-07-30 14:56 UTC, ZubkoWhatislove commented on frontend/src/common/enums/app/app-route.enum.ts
> +  CREATE_PODCAST = '/create-podcast',
```suggestion
  EDIT_PODCAST = '/podcasts/edit/:id',
```
we'll use this page for creating & editing
(check documentation)

2021-07-30 14:56 UTC, ZubkoWhatislove commented on shared/src/validation-schemas/podcast/create-podcast.validation-schema.ts
> +  [PodcastCreatePayloadKey.NAME]: Joi.string().min(1).max(20).required(),
Create enum for:
rules - podcastValidationRule
messages: podcastMessage
in the `shared/src/common/enums/validation/`

2021-07-30 14:56 UTC, ZubkoWhatislove commented on shared/src/validation-schemas/podcast/create-podcast.validation-schema.ts
> +const createPodcastSchema = Joi.object<PodcastCreatePayload>({
```suggestion
const podcast = Joi.object<PodcastCreatePayload>({
```

Check the A3 criteria

2021-07-30 14:56 UTC, ZubkoWhatislove commented on frontend/src/components/create-podcast/create-podcast.tsx
> +import { createPodcastSchema } from 'validation-schemas/validation-schemas';
```suggestion
import { podcast as podcastSchema } from 'validation-schemas/validation-schemas';
```

2021-07-30 14:56 UTC, ZubkoWhatislove commented on frontend/src/components/create-podcast/create-podcast.tsx
> +import { PodcastCreatePayloadKey } from 'jabber-shared/common/enums/enums';
don't import directly from shared packages

2021-07-30 14:56 UTC, ZubkoWhatislove commented on frontend/src/components/create-podcast/create-podcast.tsx
> +import { useForm, FieldValues } from 'react-hook-form';
move useForm for `frontend/src/hooks`

2021-07-30 14:56 UTC, ZubkoWhatislove commented on frontend/src/store/configurate-pocast/common.ts
> +  POST_PODCAST = 'podcast/post-podcast',
```suggestion
  POST_PODCAST = 'configurate/create-podcast',
```

2021-07-30 14:56 UTC, ZubkoWhatislove commented on frontend/src/components/create-podcast/create-podcast.tsx
> +      [PodcastCreatePayloadKey.USER_ID]: 7,
move it to constants
frontend/src/components/create-podcast/common/constants.ts

2021-07-31 09:32 UTC, what1s1ove requested changes

2021-07-31 09:32 UTC, what1s1ove commented on frontend/src/common/enums/app/app-route.enum.ts
> +  EDIT_PODCAST = '/podcasts/edit/:id',
```suggestion
  POCAST_EDIT_$ID = '/podcasts/edit/:id?',
```
Add `$` for dynamic params

2021-07-31 09:32 UTC, what1s1ove commented on frontend/src/components/app/app.tsx
> +import CreatePodcast from 'components/create-podcast/create-podcast';
```suggestion
import ConfiguratePodcast from 'components/configurate-podcast/configurate-podcast';
```

2021-07-31 09:32 UTC, what1s1ove commented on frontend/src/components/create-podcast/common/constants.ts
> +  [PodcastCreatePayloadKey.USER_ID]: '1',
```suggestion
  // shared/src/common/constants/user.ts
  const DEFAULT_USER_ID = -1;

  [PodcastCreatePayloadKey.USER_ID]: DEFAULT_USER_ID,
```

2021-07-31 09:32 UTC, what1s1ove commented on shared/src/common/types/podcast/podcast-create-payload.type.ts
> +  [PodcastCreatePayloadKey.USER_ID]: string;
```suggestion
  [PodcastCreatePayloadKey.USER_ID]: number;
```

2021-07-31 09:32 UTC, what1s1ove commented on shared/src/validation-schemas/podcast/create-podcast.validation-schema.ts
> +    .positive()
```suggestion
```

2021-07-31 09:32 UTC, what1s1ove commented on shared/src/validation-schemas/podcast/podcast.ts
> +export * from './create-podcast.validation-schema';
```suggestion
export { podcast } from './create-podcast.validation-schema';
```

2021-07-31 09:32 UTC, what1s1ove commented on frontend/src/store/configurate-pocast/common.ts
> +  POST_PODCAST = 'configurate/create-podcast',
```suggestion
  CREATE_PODCAST = 'configurate-podcast/create-podcast',
```

2021-07-31 09:32 UTC, what1s1ove commented on frontend/src/components/create-podcast/create-podcast.tsx
> +  const onSubmit = (data: PodcastCreatePayload): void => {
check **A9** criteria

2021-07-31 09:32 UTC, what1s1ove commented on frontend/src/components/create-podcast/create-podcast.tsx
> +      <form
move form to `frontend/src/components/create-podcast/components/configurate-podcast-form/configurate-podcast-form.tsx`

2021-07-31 19:49 UTC, Liza-Veis requested changes

2021-07-31 19:49 UTC, Liza-Veis commented on shared/src/common/constants/user.ts
> +const DEFAULT_USER_ID = -1;
Move it to user folder

2021-07-31 19:49 UTC, Liza-Veis commented on shared/src/common/enums/validation/podcast-validation-message.enum.ts
> +  USER_ID_NUMBER_FORMAT: 'User id must be integer number',
```suggestion
  USER_ID_NUMBER_FORMAT: 'User id must be an integer',
```

2021-07-31 19:49 UTC, Liza-Veis commented on frontend/src/common/constants/constants.ts
> +export { DEFAULT_USER_ID } from 'jabber-shared/common/constants/constants';
Move it to the user folder "frontend/src/common/constants/user" and then re-export from this file

2021-07-31 19:53 UTC, Liza-Veis commented
Why do you often put something in the "p" tag? If you want to add paddings you can just use styles or is there another reason?

2021-07-31 23:54 UTC, artem-totality commented
> Why do you often put something in the "p" tag? If you want to add paddings you can just use styles or is there another reason?

It was the simplest way make this padding in this situation without redundant styles.

2021-08-01 06:29 UTC, Liza-Veis submitted a review, later dismissed

2021-08-01 06:47 UTC, ZubkoWhatislove commented on shared/src/validation-schemas/podcast/create-podcast.validation-schema.ts
> +import * as Joi from 'joi';
rename file to ``shared/src/validation-schemas/podcast/podcast.validation-schema.ts

2021-08-01 06:47 UTC, ZubkoWhatislove commented on frontend/src/components/configurate-podcast/configurate-podcast.tsx
> +  };
```suggestion
  const handleCreatePodcast = (payload: PodcastCreatePayload): void => {
    dispatch(podcastActions.create(payload));
  };
```

2021-08-01 06:47 UTC, ZubkoWhatislove commented on frontend/src/components/configurate-podcast/components/configurate-podcast-form/configurate-podcast-form.tsx
> +        </div>
```suggestion
```

2021-08-01 06:47 UTC, ZubkoWhatislove commented on frontend/src/components/configurate-podcast/components/configurate-podcast-form/configurate-podcast-form.tsx
> +      </p>
```suggestion
        <Button label="Save" type={ButtonType.SUBMIT} />
```

2021-08-01 06:47 UTC, ZubkoWhatislove commented on frontend/src/components/configurate-podcast/components/configurate-podcast-form/configurate-podcast-form.tsx
> +      </p>
also, move button to fieldset (to disable it too while saving)

2021-08-01 08:26 UTC, ZubkoWhatislove approved these changes

2021-08-01 08:28 UTC, merged