Task vv/250 dont show placeholder while loading page
BinaryStudioAcademy/bsa-2021-jabber pull request #276
Opened 2021-08-24 12:09 UTC by vitalik-prog

2021-08-24 12:09 UTC, what1s1ove requested changes

2021-08-24 12:09 UTC, what1s1ove commented on frontend/src/components/podcast/podcast.tsx
> +  const isLoading = dataStatus !== DataStatus.FULFILLED && followersDataStatus !== DataStatus.FULFILLED;
what if an error?

2021-08-24 18:53 UTC, vitalik-prog commented on frontend/src/components/podcast/podcast.tsx
> +  const isLoading = dataStatus !== DataStatus.FULFILLED && followersDataStatus !== DataStatus.FULFILLED;
It will be endless loading ^-)

2021-08-25 04:54 UTC, what1s1ove submitted a review, later dismissed

2021-08-25 06:20 UTC, what1s1ove approved these changes

2021-08-25 06:20 UTC, merged