Task sf/j238 private subscription functionality
BinaryStudioAcademy/bsa-2021-jabber pull request #286
Opened 2021-08-25 10:49 UTC by Sayonarko

2021-08-25 11:44 UTC, Sayonarko commented
![](https://github.trello.services/images/mini-trello-icon.png) [Private subscription functionality](https://trello.com/c/xdeWfBpz/238-private-subscription-functionality)

2021-08-25 18:21 UTC, JuliaDzyuba submitted a review, later dismissed

2021-08-26 05:05 UTC, what1s1ove requested changes
Good! 👍

2021-08-26 05:05 UTC, what1s1ove commented on frontend/src/helpers/uuid/get-uuid/get-uuid.helper.ts
> +const getUuid = (): string => {
```suggestion
const getRandomId = (): string => {
```
don't forget to rename the file
and move it to the `string` helpers

2021-08-26 05:05 UTC, what1s1ove commented on frontend/src/components/podcast-invite/podcast-invite.tsx
> +
if we don't have an user we should redirect to the `/login page`

2021-08-26 06:28 UTC, Sayonarko commented on frontend/src/components/podcast-invite/podcast-invite.tsx
> +
`/podcasts/invite/:code` this is a private route

2021-08-26 07:36 UTC, what1s1ove approved these changes

2021-08-26 07:36 UTC, what1s1ove commented on frontend/src/components/podcast-invite/podcast-invite.tsx
> +
Good!

2021-08-26 07:36 UTC, merged