J-259 + fixed shifting markup when scroll appears
BinaryStudioAcademy/bsa-2021-jabber pull request #288
Opened 2021-08-25 11:29 UTC by vitalik-prog

2021-08-25 11:39 UTC, vitalik-prog commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix header markup. When clicked on bell icon markup shifts to the right](https://trello.com/c/NqWs1sU5/259-fix-header-markup-when-clicked-on-bell-icon-markup-shifts-to-the-right)

2021-08-25 11:48 UTC, Denidzio submitted a review, later dismissed

2021-08-25 13:39 UTC, what1s1ove requested changes

2021-08-25 13:39 UTC, what1s1ove commented on frontend/src/assets/css/scaffolding.scss
> +  width:100vw;
```suggestion
```

2021-08-25 13:39 UTC, what1s1ove commented on frontend/src/assets/css/scaffolding.scss
> -  scroll-behavior: smooth;
return it

2021-08-26 04:55 UTC, what1s1ove commented
now it is not needed

2021-08-26 04:55 UTC, closed without merging