J-263: Fix popular podcasters markup
BinaryStudioAcademy/bsa-2021-jabber pull request #289
Opened 2021-08-25 14:14 UTC by EugeniusGR

![image](https://user-images.githubusercontent.com/35200697/130806935-e20c94c7-0a41-4b53-b0f9-be65e495441b.png)

2021-08-25 14:45 UTC, Denidzio requested changes

2021-08-25 14:45 UTC, Denidzio commented on frontend/src/components/homepage/components/popular-users/popular-users.tsx
> +      )}
```suggestion
         <ul className={getAllowedClasses(styles.usersRow, popularUsers.length >=5 && styles.groupPodcastes)}>
          {popularUsers.map((user) => (
            <>
              <PopularUser key={user.id} user={user} />
            </>
          ))}
        </ul>
```

2021-08-25 14:56 UTC, Denidzio commented on frontend/src/components/homepage/components/popular-users/popular-users.tsx
> +          </>
Why did you wrap it by React.Fragment?

2021-08-25 14:57 UTC, Denidzio commented on frontend/src/components/homepage/components/popular-users/popular-users.tsx
> +          </>
I think it will cause error with 'key' prop. Check it in the console

2021-08-25 15:47 UTC, EugeniusGR commented on frontend/src/components/homepage/components/popular-users/popular-users.tsx
> +          </>
oh, I did some checks with count of users and forget to delete it, thx ;)

2021-08-25 16:01 UTC, Denidzio requested changes

2021-08-25 16:01 UTC, Denidzio commented on frontend/src/components/homepage/components/popular-users/popular-users.tsx
> +          popularUsers.length >= 5 && styles.groupPodcastes,
What does it mean 5? It should be a constant

2021-08-25 16:16 UTC, Denidzio requested changes

2021-08-25 16:16 UTC, Denidzio commented on frontend/src/components/homepage/components/popular-users/styles.module.scss
> +    margin-right: 35px;
You have used `grid-gap` already. Why you started to use` margin-right`?
![image](https://user-images.githubusercontent.com/60543500/130826952-24b4cff0-9e77-483c-848d-4c2571fa7f61.png)

2021-08-26 04:55 UTC, what1s1ove requested changes

2021-08-26 04:55 UTC, what1s1ove commented on frontend/src/components/homepage/components/popular-users/popular-users.tsx
> +          popularUsers.length >= 5 && styles.groupPodcastes,
agreed

2021-08-26 04:56 UTC, what1s1ove commented on frontend/src/components/homepage/components/popular-users/styles.module.scss
> +    margin-right: 35px;
agreed

2021-08-26 08:49 UTC, what1s1ove requested changes

2021-08-26 08:49 UTC, what1s1ove commented on frontend/src/components/homepage/components/popular-users/popular-users.tsx
> +const MAXIMUM_PODCASTERS_WITHOUT_MARKUP = 5;
move to `frontend/src/components/homepage/components/popular-users/common/constants.ts`

2021-08-26 12:01 UTC, what1s1ove approved these changes

2021-08-26 12:01 UTC, merged