Task ys/j257 episodes pagination functionality
BinaryStudioAcademy/bsa-2021-jabber pull request #290
Opened 2021-08-26 06:02 UTC by yaroslav207

2021-08-27 05:35 UTC, what1s1ove requested changes

2021-08-27 05:35 UTC, what1s1ove commented on backend/src/data/repositories/episode/episode.repository.ts
> +import {PodcastType} from "../../../../../shared/build";
🤔

2021-08-27 05:35 UTC, what1s1ove commented on backend/src/services/episode/episode.service.ts
> +import {LoadEpisodesByPodcastIdPayload} from "../../../../shared/build/common/types/episode/load-episodes-by-podcast-id-payload.type";
🤔

2021-08-27 05:35 UTC, what1s1ove commented on frontend/src/components/podcast/components/pagination/pagination.tsx
> +import { PageSizes } from './common/constants/constants';
add pagination for the `table component`

2021-08-27 05:35 UTC, what1s1ove commented on frontend/src/components/podcast/components/pagination/common/constants/page-sizes.ts
> +const PageSizes = [5, 10, 20];
```suggestion
const PAGE_SIZES = [5, 10, 20];
```

2021-08-27 22:30 UTC, EugeniusGR commented on frontend/src/components/podcast/healper/get-filter-episode/get-filter-episode.ts
> +    offset: (page - 1) * row,
mb, go const?

2021-08-28 05:23 UTC, what1s1ove requested changes

2021-08-28 05:23 UTC, what1s1ove commented on frontend/src/components/podcast/components/components.ts
> +export { default as Pagination } from './pagination/pagination';
this should be a part of `table` common component

2021-08-28 05:23 UTC, what1s1ove commented on frontend/src/components/podcast/components/pagination/pagination.tsx
> +    const newPage = Number(e.target.value);
```suggestion
  const changePages = (evt: React.ChangeEvent<HTMLInputElement>): void => {
    const newPage = Number(evt.target.value);
```

2021-08-28 05:23 UTC, what1s1ove commented on frontend/src/components/podcast/components/pagination/pagination.tsx
> +    setPage(pageIndex - 1);
add constants for all magic numbers

2021-08-28 05:23 UTC, what1s1ove commented on frontend/src/components/podcast/components/pagination/pagination.tsx
> +  const changePageSizes = (e: React.ChangeEvent<HTMLSelectElement>): void => {
```suggestion
  const handlePageSizesChange = (e: React.ChangeEvent<HTMLSelectElement>): void => {
```

2021-08-28 05:23 UTC, what1s1ove commented on frontend/src/components/podcast/components/pagination/pagination.tsx
> +  setPage: (page: number) => void;
check **A9** criteria

2021-08-28 05:23 UTC, what1s1ove commented on frontend/src/components/podcast/components/pagination/pagination.tsx
> +        PREV
do uppercase with styles

2021-08-28 05:23 UTC, what1s1ove commented on frontend/src/components/podcast/components/pagination/pagination.tsx
> +        NEXT
do uppercase with styles

2021-08-28 05:23 UTC, what1s1ove commented on frontend/src/components/podcast/healper/get-filter-episode/get-filter-episode.ts
> +    offset: (page - 1) * row,
agreed

2021-08-28 05:23 UTC, what1s1ove commented on frontend/src/components/podcast/healper/get-filter-episode/get-filter-episode.ts
> +export const getFilterEpisode = (page: number, row: number): EpisodeLoadFilter => {
export only at the bottom

2021-08-28 05:23 UTC, what1s1ove commented on frontend/src/components/podcast/common/constatnts/constants.ts
> +export const DEFAULT_EPISODE_PAGINATION = {
export only at the bottom

2021-08-28 05:23 UTC, what1s1ove commented on frontend/src/components/podcast/podcast.tsx
> +      page: 1,
add constants for all magic numbers

2021-08-28 05:23 UTC, what1s1ove commented on frontend/src/components/podcast/podcast.tsx
> +              <Pagination
pagination should be a part of `table component`

2021-08-28 14:47 UTC, what1s1ove requested changes

2021-08-28 14:47 UTC, what1s1ove commented on frontend/src/components/common/table/components/pagination/pagination.tsx
> +  handleSetRow: (row: number) => void;
check **A8** criteria

2021-08-28 14:47 UTC, what1s1ove commented on frontend/src/components/common/table/components/pagination/pagination.tsx
> +  const changePages = (evt: React.ChangeEvent<HTMLInputElement>): void => {
check **A9** criteria

2021-08-28 14:47 UTC, what1s1ove commented on frontend/src/components/common/table/table.tsx
> +  totalCountEpisodes: number;
check **A8** criteria
add new props `hasPagination` and make all these props optionals

2021-08-28 14:47 UTC, what1s1ove commented on frontend/src/components/podcast/healper/get-filter-episode/get-filter-episode.ts
> +import { EpisodeLoadFilter } from 'common/types/types';
frontend/src/components/podcast/healper/get-filter-episode/get-filter-episode.helper.ts

2021-08-28 14:47 UTC, what1s1ove commented on frontend/src/components/podcast/podcast.tsx
> +  const setRowEpisodeFilter = (row: number): void => {
check **A9** criteria

2021-08-28 17:07 UTC, what1s1ove requested changes

2021-08-28 17:07 UTC, what1s1ove commented on frontend/src/components/podcast/healper/healper.ts
> +export { getFilterEpisode } from './get-filter-episode/get-filter-episode.healper';
```suggestion
export { getFilterEpisode } from './get-filter-episode/get-filter-episode.helper';
```

2021-08-29 06:33 UTC, what1s1ove approved these changes

2021-08-29 06:33 UTC, merged