Task as/j237 comment likes functionality
BinaryStudioAcademy/bsa-2021-jabber pull request #300
Opened 2021-08-26 23:35 UTC by qwiz1

![2021-08-27 02_11_10-Jabber](https://user-images.githubusercontent.com/22223694/131049160-e78b6dd9-ae97-4910-9015-3595883a995a.png)
![2021-08-27 02_11_31-Jabber](https://user-images.githubusercontent.com/22223694/131049169-a5af5b54-057d-407e-a5b6-f05bd8c77896.png)

2021-08-27 05:37 UTC, what1s1ove requested changes

2021-08-27 05:37 UTC, what1s1ove commented on backend/package-lock.json
> -      "requires": {
it shouldn't be changed

2021-08-27 05:37 UTC, what1s1ove commented on backend/src/api/api.ts
> +  initCommentReactionsApi({
we don't need this api
all APIs should be by the `/comments` route

2021-08-27 10:02 UTC, JuliaDzyuba submitted a review, later dismissed

2021-08-28 05:14 UTC, what1s1ove requested changes

2021-08-28 05:14 UTC, what1s1ove commented on backend/src/common/enums/app/error-message.enum.ts
> +  ALREADY_LIKED = 'Already liked',
not sure that we need it because we can toggle like

2021-08-28 05:14 UTC, what1s1ove commented on backend/src/data/migrations/20210822152011_add_comment_reactions_table.ts
> +    table.integer('comment_id').notNullable().references('id').inTable('comments').onDelete('CASCADE');
```suggestion
    table.integer('user_id').notNullable().references('id').inTable('users');
    table.integer('comment_id').notNullable().references('id').inTable('comments');
```
avoid CASCADE in out project

2021-08-28 05:14 UTC, what1s1ove commented on frontend/src/common/types/comment/comment-form-create-payload.type.ts
> +  [CommentCreatePayloadKey.COMMENT_REACTIONS]: CommentReaction[];
it shouldn't be while creating comment

2021-08-28 05:14 UTC, what1s1ove commented on frontend/src/components/common/comment-item/comment-item.tsx
> +  onCommentLike?: (payload: CommentReactionCreatePayload) => void;
```suggestion
  onCommentLikeToggle?: (payload: CommentReactionCreatePayload) => void;
```
we can toggle it

2021-08-28 05:14 UTC, what1s1ove commented on frontend/src/components/common/comment-item/comment-item.tsx
> +  const handleLikeComment = (): void => {
```suggestion
  const handleCommentLikeToggle = (): void => {
```

2021-08-28 05:14 UTC, what1s1ove commented on frontend/src/components/common/comment-item/comment-item.tsx
> +    styles[`like${filled}`],
```suggestion
  const allowedClasses = getAllowedClasses(
    styles.likeButton,
     sLiked  && styles.likeButtonFilled,
```

2021-08-28 05:14 UTC, what1s1ove commented on frontend/src/components/common/comments-list/comments-list.tsx
> +        const isLiked = item.commentReactions?.some((reaction) => reaction.userId === user?.id);
create `checkIsLiked` helper and move it to `frontend/src/components/common/comments-list/helpers/`

2021-08-28 05:14 UTC, what1s1ove commented on frontend/src/components/common/create-comment-form/common/constants.ts
> +  [CommentCreatePayloadKey.COMMENT_REACTIONS]: [],
```suggestion
```

2021-08-28 05:14 UTC, what1s1ove commented on frontend/src/components/episode/episode.tsx
> +  const handleCommentLike = (payload: CommentReactionCreatePayload): void => {
```suggestion
  const handleCommentLikeToggle = (payload: CommentReactionCreatePayload): void => {
```

2021-08-28 05:14 UTC, what1s1ove commented on frontend/src/store/episode/actions.ts
> +const likeComment = createAsyncThunk <Comment, CommentReactionCreatePayload, AsyncThunkConfig>
```suggestion
const toggleCommentLike = createAsyncThunk <Comment, CommentReactionCreatePayload, AsyncThunkConfig>
```

2021-08-29 06:45 UTC, what1s1ove requested changes

2021-08-29 06:45 UTC, what1s1ove commented on backend/src/services/episode/episode.service.ts
> +    const comments = await this.#commentService.getAllByEpisodeId(episode.id);
it can return empty array. any array is always true

2021-08-29 06:45 UTC, what1s1ove commented on frontend/src/components/common/comment-item/comment-item.tsx
> +  toggleCommentLike?: (commentId: number) => void;
check **A9** criteria

2021-08-29 06:45 UTC, what1s1ove commented on frontend/src/components/common/comment-item/comment-item.tsx
> +            {comment.commentReactions?.length ?? 0}
```suggestion
            {comment.commentReactions?.length ?? DEFAULT_COMMENT_COUNT}
```

2021-08-29 06:45 UTC, what1s1ove commented on frontend/src/components/common/comments-list/comments-list.tsx
> +  toggleCommentLike?: (commentId: number) => void;
```suggestion
  toggleCommentLike?: (commentId: number) => void;
```
check **A9** criteria

2021-08-29 06:45 UTC, what1s1ove commented on frontend/src/components/common/comments-list/helpers/check-is-liked/check-is-liked.ts
> +import { Comment } from 'common/types/types';
`frontend/src/components/common/comments-list/helpers/check-is-liked/check-is-liked.helper.ts`

2021-08-29 06:45 UTC, what1s1ove commented on frontend/src/store/episode/actions.ts
> +  const checkIsLiked = currentComment.commentReactions.some((reaction) => reaction.userId === auth.user?.id);
```suggestion
  const isLiked = currentComment.commentReactions.some((reaction) => reaction.userId === auth.user?.id);
```
you already have this functionality in the `checkIsLiked` helper. move this comment to the `frontend/src/helper/comment` and reuse it here

2021-08-29 06:45 UTC, what1s1ove commented on frontend/src/store/episode/reducer.ts
> +    const commetns = [action.payload, ...filtered].sort((commentA, commentB) => commentB.id - commentA.id);
use `getSortedItems` helper here
also, sort by `createAt` please

2021-08-29 11:33 UTC, what1s1ove approved these changes

2021-08-29 11:34 UTC, merged