Task jd/j270 output followers on the users page
BinaryStudioAcademy/bsa-2021-jabber pull request #303
Opened 2021-08-27 13:04 UTC by JuliaDzyuba

have some problem with query

2021-08-27 15:07 UTC, Denidzio requested changes

2021-08-27 15:07 UTC, Denidzio commented on frontend/src/components/user-followers/user-followers.tsx
> +// import FollowerItem from './components/follower-item/follower-item';
Redundant commnet

2021-08-27 15:07 UTC, Denidzio commented on frontend/src/components/user-followers/user-followers.tsx
> +  console.log('followers', followers);
Redundant `console.log`

2021-08-27 15:07 UTC, Denidzio commented on frontend/src/components/user-followers/user-followers.tsx
> +        ))} */}
You forgot to remove the comment

2021-08-27 15:07 UTC, Denidzio commented on frontend/src/components/user-profile/user-profile.tsx
> +            {/* </div> */}
Also forgot to remove the comment

2021-08-27 15:07 UTC, Denidzio commented on frontend/src/store/user-follower/actions.ts
> +    console.log('followers', followers);
Redundant `console.log`

2021-08-27 22:32 UTC, EugeniusGR submitted a review, later dismissed

2021-08-28 05:07 UTC, what1s1ove approved these changes

2021-08-28 05:07 UTC, merged