Task av/j272 add forgot password functionality
BinaryStudioAcademy/bsa-2021-jabber pull request #305
Opened 2021-08-27 14:41 UTC by artem-totality

2021-08-27 22:35 UTC, EugeniusGR submitted a review, later dismissed

2021-08-28 03:56 UTC, JuliaDzyuba submitted a review, later dismissed

2021-08-28 05:28 UTC, what1s1ove requested changes

2021-08-28 05:28 UTC, what1s1ove commented on backend/src/services/auth/auth.service.ts
> +    const newPassword = getRandomId(6);
add const for it

2021-08-28 05:28 UTC, what1s1ove commented on backend/src/services/mailer/mailer.service.ts
> +        from: this.#mailerEmail,
let's pass it from params

2021-08-28 05:28 UTC, what1s1ove commented on backend/src/services/mailer/mailer.service.ts
> +    this.#mailerEmail = mailerEmail;
```suggestion
```

2021-08-28 05:28 UTC, what1s1ove commented on shared/src/common/types/user/user-reset-password-payload.type.ts
> +type UserResetPasswordPayload = UserPayload;
```suggestion
type UserResetPasswordPayload = {
  // describe it
};
```

2021-08-28 14:44 UTC, what1s1ove approved these changes

2021-08-28 14:44 UTC, merged