J-292: + added show password icon on the auth pages
BinaryStudioAcademy/bsa-2021-jabber pull request #320
Opened 2021-08-29 14:55 UTC by JuliaDzyuba

![291718](https://user-images.githubusercontent.com/60258687/131254841-65e58bf4-71c1-4a65-a3c0-7395a35bf136.png)

2021-08-29 14:57 UTC, what1s1ove requested changes

2021-08-29 14:57 UTC, what1s1ove commented on frontend/src/components/auth/components/sign-up-form/sign-up-form.tsx
> +          ></button>
```suggestion
          >
            <span className="visually-hidden">Toggle password visibility</span>
          </button>
```

2021-08-29 14:57 UTC, what1s1ove commented on frontend/src/components/auth/components/sign-in-form/sign-in-form.tsx
> +          ></button>
```suggestion
          >
            <span className="visually-hidden">Toggle password visibility</span>
          </button>
```

2021-08-29 15:11 UTC, Denidzio requested changes

2021-08-29 15:11 UTC, Denidzio commented on frontend/src/assets/img/eye-invisible.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
Let's [compress ](shrinkme.app) it
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 469.44 469.44">
    <path d="M231.147 160.373l67.2 67.2.32-3.52c0-35.307-28.693-64-64-64l-3.52.32z"/>
    <path d="M234.667 117.387c58.88 0 106.667 47.787 106.667 106.667 0 13.76-2.773 26.88-7.573 38.933l62.4 62.4c32.213-26.88 57.6-61.653 73.28-101.333-37.013-93.653-128-160-234.773-160-29.867 0-58.453 5.333-85.013 14.933l46.08 45.973c12.052-4.693 25.172-7.573 38.932-7.573zM21.333 59.253l48.64 48.64 9.707 9.707C44.48 145.12 16.64 181.707 0 224.053c36.907 93.653 128 160 234.667 160 33.067 0 64.64-6.4 93.547-18.027l9.067 9.067 62.187 62.293 27.2-27.093L48.533 32.053l-27.2 27.2zM139.307 177.12l32.96 32.96c-.96 4.587-1.6 9.173-1.6 13.973 0 35.307 28.693 64 64 64 4.8 0 9.387-.64 13.867-1.6l32.96 32.96c-14.187 7.04-29.973 11.307-46.827 11.307-58.88 0-106.667-47.787-106.667-106.667 0-16.853 4.267-32.64 11.307-46.933z"/>
</svg>`

2021-08-29 15:11 UTC, Denidzio commented on frontend/src/components/auth/components/sign-in-form/sign-in-form.tsx
> +            className={isVisible ? getAllowedClasses(styles.showPasswordBtn, styles.visible) : styles.showPasswordBtn}
```suggestion
            className={getAllowedClasses(styles.showPasswordBtn, isVisible && styles.visible)}
```

2021-08-29 15:11 UTC, Denidzio commented on frontend/src/components/auth/components/sign-up-form/sign-up-form.tsx
> +import { getAllowedClasses } from 'helpers/helpers';
Import order

2021-08-29 15:11 UTC, Denidzio commented on frontend/src/components/auth/components/sign-up-form/sign-up-form.tsx
> +            className={isVisible ? getAllowedClasses(styles.showPasswordBtn, styles.visible) : styles.showPasswordBtn}
```suggestion
           className={getAllowedClasses(styles.showPasswordBtn, isVisible && styles.visible)}
```

2021-08-29 15:15 UTC, Denidzio commented on frontend/src/components/auth/components/sign-in-form/sign-in-form.tsx
> +  const [isVisible, setIsVisible] = useState<boolean>(false);
It is not entirely clear from the name what is visible

2021-08-29 19:12 UTC, Denidzio requested changes

2021-08-29 19:12 UTC, Denidzio commented on frontend/src/assets/img/eye-invisible.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 469.44 469.44"> <path d="M231.147 160.373l67.2 67.2.32-3.52c0-35.307-28.693-64-64-64l-3.52.32z"/> <path d="M234.667 117.387c58.88 0 106.667 47.787
You can format this. Nothing bad will happen

2021-08-29 19:12 UTC, Denidzio commented on frontend/src/components/auth/components/sign-in-form/sign-in-form.tsx
>    const handleToggleVisible = (): void => {
`handleToggleVisible` what? Let's rename it too

2021-08-30 04:06 UTC, what1s1ove approved these changes

2021-08-30 04:07 UTC, merged