Task av/j300 copy podcast invite link
BinaryStudioAcademy/bsa-2021-jabber pull request #321
Opened 2021-08-29 16:03 UTC by artem-totality

2021-08-29 22:47 UTC, yaroslav207 approved these changes, later dismissed

2021-08-30 04:06 UTC, what1s1ove requested changes

2021-08-30 04:06 UTC, what1s1ove commented on backend/src/data/models/podcast/podcast.model.ts
> +    },
```suggestion
```
this is private info. model shouldn't change

2021-08-30 04:06 UTC, what1s1ove commented on frontend/src/components/podcast/podcast.tsx
> +import { notification as notificationService } from 'services/services';
you can't use services directly in the components

2021-08-30 10:37 UTC, what1s1ove approved these changes

2021-08-30 10:38 UTC, merged