Task sf/j294 add favourite episodes functionality
BinaryStudioAcademy/bsa-2021-jabber pull request #322
Opened 2021-08-29 18:34 UTC by Sayonarko

![favour](https://user-images.githubusercontent.com/35679428/131261541-b9bdbba6-2f99-4313-b5c7-b8aacf8b70c9.png)

2021-08-30 04:25 UTC, what1s1ove requested changes
add podcast name to the table
move episode-table back, because we will have a different tables

2021-08-30 04:25 UTC, what1s1ove commented on backend/src/api/episodes/episodes.api.ts
> +    EpisodesApiPath.FAVOURITES_$ID,
```suggestion
    EpisodesApiPath.FAVOURITES_$USER_ID,
```

2021-08-30 04:25 UTC, what1s1ove commented on frontend/src/store/user-favourite-episodes/actions.ts
> +    return await episodeApi.getFavoriteEpisodesByUserId(payload);
```suggestion
    return episodeApi.getFavoriteEpisodesByUserId(payload);
```

2021-08-30 10:43 UTC, JuliaDzyuba approved these changes, later dismissed

2021-08-31 05:42 UTC, what1s1ove requested changes

2021-08-31 05:42 UTC, what1s1ove commented on backend/src/api/episodes/episodes.api.ts
> +    handleAsyncApi(async (req, res) => {
always add validation for requests which use body

2021-08-31 05:42 UTC, what1s1ove commented on frontend/src/components/user-favourite-episodes/components/favourite-episode-table/helpers/get-formatted-date.ts
> +import { DateFormatType } from 'common/enums/enums';
`frontend/src/components/user-favourite-episodes/components/favourite-episode-table/helpers/get-formatted-date/get-formatted-date.helper.ts`

2021-08-31 05:42 UTC, what1s1ove commented on shared/src/common/types/episode/episode.type.ts
> +  podcast?: Podcast;
we can't change the origin episode type

2021-08-31 15:27 UTC, what1s1ove submitted a review, later dismissed

2021-08-31 15:55 UTC, what1s1ove approved these changes

2021-08-31 15:56 UTC, merged