Task av/j296 add dynamic periodicity
BinaryStudioAcademy/bsa-2021-jabber pull request #338
Opened 2021-09-01 08:06 UTC by artem-totality

2021-09-01 12:53 UTC, JuliaDzyuba submitted a review, later dismissed

2021-09-01 14:35 UTC, Denidzio requested changes

2021-09-01 14:35 UTC, Denidzio commented on frontend/src/components/podcast/helpers/get-podcast-periodicity/get-podcast-periodicity.helper.ts
> +  const firstDate = uniqueSortedEpisodesDates[0];
What does it mean `0`? Let's use [destructuring assignment](https://javascript.info/destructuring-assignment)
```suggestion
  const [firstDate] = uniqueSortedEpisodesDates;
```

2021-09-01 14:35 UTC, Denidzio commented on frontend/src/components/podcast/helpers/get-podcast-periodicity/get-podcast-periodicity.helper.ts
> +    uniqueSortedEpisodesDates[uniqueSortedEpisodesDates.length - 1];
You have a lot 'magic numbers' in this file. Let's use constant

2021-09-02 11:47 UTC, what1s1ove requested changes
discussed that should be changed

2021-09-03 05:48 UTC, what1s1ove requested changes

2021-09-03 05:48 UTC, what1s1ove commented on frontend/src/components/podcast/helpers/get-podcast-periodicity/get-podcast-periodicity.helper.ts
> +  );
you `getSortedItems` helper here

2021-09-03 05:48 UTC, what1s1ove commented on frontend/src/components/podcast/helpers/get-podcast-periodicity/get-podcast-periodicity.helper.ts
> +  }
we need move ranges
1 - 3 days - should be `daily`
4 - 10  days - should be `weekly`
otherwise -  `monthly`

2021-09-03 06:51 UTC, what1s1ove requested changes

2021-09-03 06:51 UTC, what1s1ove commented on frontend/src/components/podcast/helpers/get-podcast-periodicity/get-podcast-periodicity.helper.ts
> +  );
don't fixed

2021-09-03 08:12 UTC, what1s1ove approved these changes

2021-09-03 08:13 UTC, merged