Task as/j15 episode page add route
BinaryStudioAcademy/bsa-2021-jabber pull request #34
Opened 2021-07-30 13:15 UTC by qwiz1

2021-07-30 13:24 UTC, Denidzio approved these changes, later dismissed

2021-07-30 13:24 UTC, Denidzio commented on backend/src/api/episodes/episodes.api.ts
> +      return res.json(await episodeService.getById(req.params.id)).status(HttpCode.OK);
It can be on one-line

2021-07-30 13:29 UTC, qwiz1 commented on backend/src/api/episodes/episodes.api.ts
> +      return res.json(await episodeService.getById(req.params.id)).status(HttpCode.OK);
Don't exactly understand what you mean

2021-07-30 13:33 UTC, ZubkoWhatislove requested changes

2021-07-30 13:33 UTC, ZubkoWhatislove commented on shared/src/common/enums/api/episodes-api-path.enum.ts
> +  ID = '/:id',
```suggestion
  $ID = '/:id',
```
dynamic parametres should be with `$`

2021-07-30 13:37 UTC, ZubkoWhatislove requested changes

2021-07-30 13:37 UTC, ZubkoWhatislove commented on backend/src/services/episode/episode.service.ts
> +    return this.#episodeRepository.getById(id);
if you don't find episode with the id you must to throw the http-error

2021-07-30 14:03 UTC, artem-totality approved these changes, later dismissed

2021-07-30 18:45 UTC, ZubkoWhatislove requested changes

2021-07-30 18:45 UTC, ZubkoWhatislove commented on backend/src/services/episode/episode.service.ts
> +      throw new HttpError({ status: 404, message: 'Episode does not exist!' });
```suggestion
      throw new HttpError({ status: 404, message: 'Episode does not exist!' });
```
use http code for status
and create `ErrorMessage` enum in `backend/src/common/enums/app`

2021-07-31 06:06 UTC, ZubkoWhatislove requested changes

2021-07-31 06:06 UTC, ZubkoWhatislove commented on backend/src/services/episode/episode.service.ts
> +      throw new HttpError({ status: HttpCode.NOT_FOUND, message: ErrorMessage.NOT_FOUND });
Previously you have the more readable error message. Let's replace it with `Entity not found.`

2021-07-31 08:21 UTC, ZubkoWhatislove approved these changes

2021-07-31 08:22 UTC, yevhenprybytok approved these changes

2021-07-31 08:22 UTC, merged