Task as/j305 pagination design according the design
BinaryStudioAcademy/bsa-2021-jabber pull request #346
Opened 2021-09-01 20:01 UTC by qwiz1

![2021-09-01 21_47_40-Jabber](https://user-images.githubusercontent.com/22223694/131736206-7b4a4563-0048-464d-8ac5-68f94b833db4.png)
![2021-09-01 21_48_11-Jabber](https://user-images.githubusercontent.com/22223694/131736210-9b8c98a1-d51d-4f15-9a2b-20f3e046120c.png)

2021-09-01 20:24 UTC, artem-totality approved these changes, later dismissed

2021-09-02 05:50 UTC, JuliaDzyuba submitted a review, later dismissed

2021-09-02 05:53 UTC, what1s1ove requested changes

2021-09-02 05:53 UTC, what1s1ove commented on frontend/src/components/user-profile/user-profile.tsx
> +            <Pagination
add pagination to table component

2021-09-02 05:53 UTC, what1s1ove commented on frontend/src/components/common/table/table.tsx
> +// import { Pagination } from 'components/common/common';
add pagination component here

2021-09-02 05:54 UTC, what1s1ove requested changes
remove 'showing'
everything should be as in the design

2021-09-02 10:00 UTC, what1s1ove requested changes

2021-09-02 10:00 UTC, what1s1ove commented on frontend/src/components/common/table/table.tsx
> +  pageCount: number;
not all tables should be with pagination 
move it back

2021-09-02 11:42 UTC, what1s1ove approved these changes

2021-09-02 11:43 UTC, merged