Task av/j319 add photo description status for playlist entity
BinaryStudioAcademy/bsa-2021-jabber pull request #351
Opened 2021-09-02 14:12 UTC by artem-totality

2021-09-02 14:14 UTC, qwiz1 reviewed
Can we do everything in one migration?

2021-09-02 14:24 UTC, artem-totality commented
I thought I needed separate migrations

2021-09-02 15:29 UTC, EugeniusGR submitted a review, later dismissed

2021-09-02 16:48 UTC, what1s1ove requested changes

2021-09-02 16:48 UTC, what1s1ove commented on backend/src/data/migrations/20210902083058_add_cover_id_to_playlists.ts
> +import { Knex } from 'knex';
make all changes in one migration

2021-09-03 05:43 UTC, what1s1ove approved these changes

2021-09-03 05:43 UTC, merged