Task ys/j352 activate notification icon bell
BinaryStudioAcademy/bsa-2021-jabber pull request #370
Opened 2021-09-04 13:39 UTC by yaroslav207

![image](https://user-images.githubusercontent.com/75075327/132096424-110f8cc6-129b-40d0-9cde-05b8d91a2f17.png)

2021-09-04 16:21 UTC, what1s1ove requested changes

2021-09-04 16:21 UTC, what1s1ove commented on frontend/src/components/common/header/header.tsx
> +  useEffect(() => {
do it in the app component

2021-09-05 15:28 UTC, JuliaDzyuba submitted a review, later dismissed

2021-09-06 04:13 UTC, what1s1ove requested changes

2021-09-06 04:13 UTC, what1s1ove commented on frontend/src/components/app/app.tsx
> +  useEffect(() => {
make it in the useEffect above

2021-09-06 08:32 UTC, what1s1ove approved these changes

2021-09-06 08:32 UTC, merged