task-sf/J354-bug-incorrect-count-showing-rows-in-episode-table
BinaryStudioAcademy/bsa-2021-jabber pull request #371
Opened 2021-09-04 13:42 UTC by Sayonarko

![episode](https://user-images.githubusercontent.com/35679428/132096461-357f5ffb-3d9b-416e-9a7c-26701977a539.png)

2021-09-04 16:20 UTC, what1s1ove requested changes

2021-09-04 16:20 UTC, what1s1ove commented on frontend/src/components/common/pagination/pagination.tsx
> +  const showingRows = totalRowsCount && defaultPaginationRows
create helper for it

2021-09-04 23:22 UTC, qwiz1 approved these changes

2021-09-05 15:19 UTC, JuliaDzyuba approved these changes

2021-09-06 04:13 UTC, what1s1ove approved these changes

2021-09-06 04:14 UTC, merged