Task jd/j334 implement playlists id page
BinaryStudioAcademy/bsa-2021-jabber pull request #375
Opened 2021-09-05 03:46 UTC by JuliaDzyuba

2021-09-05 07:57 UTC, Sayonarko commented on backend/src/data/repositories/episode/episode.repository.ts
> +      .where('playlists_episodes.playlist_id', playlistId)
```suggestion
      .where('playlistEpisodes.playlist_id', playlistId)
```

2021-09-05 07:57 UTC, Sayonarko commented on backend/src/data/repositories/episode/episode.repository.ts
> +      .where('playlists_episodes.playlist_id', id)
```suggestion
      .where('playlistEpisodes.playlist_id', id)
```

2021-09-06 04:24 UTC, what1s1ove requested changes

2021-09-06 04:24 UTC, what1s1ove commented on backend/src/services/episode/episode.service.ts
> +  public async getPlaylistEpisodesByQueryByPLaylistId(payload: LoadPlaylistEpisodesPayload): Promise<PlaylistEpisodeResponse> {
we don't need pagination on the page

2021-09-06 04:24 UTC, what1s1ove commented on backend/src/data/repositories/episode/episode.repository.ts
> +  public getPlaylistEpisodesCountByUserId(id: number): Promise<number> {
we don't pagination for this page

2021-09-06 04:24 UTC, what1s1ove commented on backend/src/data/repositories/episode/episode.repository.ts
> +  public getPlaylistEpisodesByQueryByPLaylistId({ playlistId, filter }: LoadPlaylistEpisodesPayload): Promise<TEpisodeWithPodcast[]> {
```suggestion
  public getEpisodesByPLaylistId({ playlistId, filter }: LoadPlaylistEpisodesPayload): Promise<TEpisodeWithPodcast[]> {
```

2021-09-06 04:24 UTC, what1s1ove commented on frontend/src/store/playlist/reducer.ts
> +  totalCount: 0,
```suggestion
```

2021-09-06 04:25 UTC, what1s1ove requested changes

2021-09-06 04:25 UTC, what1s1ove commented on backend/src/services/episode/episode.service.ts
> +  public async getPlaylistEpisodesByQueryByPLaylistId(payload: LoadPlaylistEpisodesPayload): Promise<PlaylistEpisodeResponse> {
```suggestion
  public async getAllByPlaylistId(payload: LoadPlaylistEpisodesPayload): Promise<PlaylistEpisodeResponse> {
```

2021-09-06 04:33 UTC, what1s1ove requested changes

2021-09-06 04:33 UTC, what1s1ove commented on backend/src/data/repositories/episode/episode.repository.ts
> +    return this.#EpisodeModel
also, return only public episodes

2021-09-06 11:12 UTC, what1s1ove requested changes
remove all thing that you don't need

2021-09-06 11:12 UTC, what1s1ove commented on shared/src/common/types/playlist-episode/playlist-episode-response.type.ts
> +type PlaylistEpisodeResponse = {
delete it

2021-09-06 12:36 UTC, what1s1ove approved these changes

2021-09-06 12:36 UTC, merged