Task sf/j368 validate query for user profile
BinaryStudioAcademy/bsa-2021-jabber pull request #397
Opened 2021-09-06 19:31 UTC by Sayonarko

2021-09-06 19:40 UTC, artem-totality commented on backend/src/middlewares/check-params-is-valid/check-params-is-valid.middleware.ts
> +      if (isNaN(Number(param))) {
What about id = 2147483648 and greater? 😉

2021-09-07 00:03 UTC, artem-totality submitted a review, later dismissed

2021-09-07 05:10 UTC, what1s1ove requested changes

2021-09-07 05:10 UTC, what1s1ove commented on backend/src/middlewares/check-params-is-valid/check-params-is-valid.middleware.ts
> +const checkParamsIsValid = (): RequestHandler => {
but we can have not only id in parameters
we should create something more specific for it

2021-09-07 12:34 UTC, what1s1ove requested changes

2021-09-07 12:34 UTC, what1s1ove commented on backend/src/middlewares/check-params-is-valid/check-params-is-valid.middleware.ts
> +    const params = Object.values(RouterParamsId);
do it as in the `checkAuthMiddleware` (pass this params through params)

2021-09-08 12:05 UTC, what1s1ove requested changes

2021-09-08 12:05 UTC, what1s1ove commented on backend/src/common/enums/express/router-params.enum.ts
> +enum RouterParams {
```suggestion
enum RouterParam {
```
enum should be always singular

2021-09-08 12:05 UTC, what1s1ove commented on backend/src/middlewares/check-params-is-valid/check-params-is-valid.middleware.ts
> +        if (isNaN(Number(checkParam)) || Number(checkParam) > MAX_POSSIBLE_ID) {
```suggestion
      if (checkParam && isNaN(Number(checkParam)) || Number(checkParam) > MAX_POSSIBLE_ID) {
```
and add variable for it

2021-09-08 12:36 UTC, what1s1ove approved these changes

2021-09-08 12:37 UTC, merged