Task as/j374: + pulse animation
BinaryStudioAcademy/bsa-2021-jabber pull request #402
Opened 2021-09-07 09:04 UTC by qwiz1

2021-09-07 09:13 UTC, what1s1ove requested changes

2021-09-07 09:13 UTC, what1s1ove commented on frontend/src/components/episode/styles.module.scss
> +@keyframes pulse {
add it for the root level (create new keyframe.scss file)

2021-09-07 18:34 UTC, JuliaDzyuba approved these changes

2021-09-08 05:00 UTC, what1s1ove approved these changes

2021-09-08 05:01 UTC, merged