Task sf/j63 add jwt password functionality
BinaryStudioAcademy/bsa-2021-jabber pull request #60
Opened 2021-08-02 12:41 UTC by Sayonarko

2021-08-02 13:02 UTC, ZubkoWhatislove requested changes

2021-08-02 13:02 UTC, ZubkoWhatislove commented on backend/src/config/passport.config.ts
> +import passport from 'passport';
move it to the `Passport` service

2021-08-02 16:06 UTC, Denidzio submitted a review, later dismissed

2021-08-02 19:46 UTC, yevhenprybytok approved these changes, later dismissed

2021-08-03 10:22 UTC, ZubkoWhatislove approved these changes

2021-08-03 10:23 UTC, merged