Task av/j50 attach photo for podcast functionality
BinaryStudioAcademy/bsa-2021-jabber pull request #61
Opened 2021-08-02 13:26 UTC by artem-totality

2021-08-02 16:17 UTC, Sayonarko submitted a review, later dismissed

2021-08-02 20:02 UTC, yevhenprybytok requested changes

2021-08-02 20:02 UTC, yevhenprybytok commented on frontend/src/components/configurate-podcast/components/configurate-podcast-image/configurate-podcast-image.tsx
> +          src={cover ? cover.url : logoCut}
```suggestion
          src={cover?.url ?? logoCut}
```

2021-08-02 20:02 UTC, yevhenprybytok commented on frontend/src/components/configurate-podcast/components/configurate-podcast-image/configurate-podcast-image.tsx
> +import { useAppSelector, useRef } from 'hooks/hooks';
Is this component can only be used in the podcast page?

2021-08-02 20:02 UTC, yevhenprybytok commented on frontend/src/services/image-api/image-api.service.ts
> +  public async uploadImage(file: File, userId = 1): Promise<Image> {
What's this userId for?

2021-08-03 04:39 UTC, ZubkoWhatislove requested changes

2021-08-03 04:39 UTC, ZubkoWhatislove commented on backend/src/api/api.ts
> +import { initFileApi } from './image/image.api';
```suggestion
```

2021-08-03 04:39 UTC, ZubkoWhatislove commented on backend/src/api/image/image.api.ts
> +import { Router } from 'express';
we don't want this api

2021-08-03 04:39 UTC, ZubkoWhatislove commented on frontend/src/store/configurate-podcast/reducer.ts
> +  image: Image | null;
```suggestion
```

2021-08-03 04:39 UTC, ZubkoWhatislove commented on frontend/src/store/configurate-podcast/actions.ts
> +});
```suggestion
```

2021-08-03 04:39 UTC, ZubkoWhatislove commented on frontend/src/services/image-api/image-api.service.ts
> +import {
we don't want this service

2021-08-03 05:52 UTC, ZubkoWhatislove requested changes

2021-08-03 05:52 UTC, ZubkoWhatislove commented on shared/src/validation-schemas/image/image.validation-schema.ts
> +import * as Joi from 'joi';
remove

2021-08-03 05:52 UTC, ZubkoWhatislove commented on shared/src/common/types/image/image-upload.type.ts
> +type ImageUploadPayload = {
remove it

2021-08-03 05:52 UTC, ZubkoWhatislove commented on shared/src/common/enums/validation/image-validation-message.enum.ts
> +const ImageValidationMessage = {
remove it

2021-08-03 05:52 UTC, ZubkoWhatislove commented on shared/src/common/enums/image/image-upload-key.enum.ts
> +enum ImageUploadKey {
remove it

2021-08-03 05:52 UTC, ZubkoWhatislove commented on frontend/src/store/configurate-podcast/actions.ts
> +// prettier-ignore
```suggestion
```

2021-08-03 05:52 UTC, ZubkoWhatislove commented on frontend/src/services/datauri/datauri.service.ts
> +class Datauri {
just create a helper `getDataUrl` and move it to the `frontend/src/helpers/file`

2021-08-03 08:04 UTC, ZubkoWhatislove requested changes

2021-08-03 08:04 UTC, ghost commented on backend/src/data/models/podcast/podcast.model.ts
> +  static get relationMappings(): any {
```suggestion
  static relationMappings = {
```

2021-08-03 08:04 UTC, ghost commented on frontend/src/helpers/file/get-data-url/get-data-url.ts
> +const getDataUrl = async (file: File): Promise<string> => {
```suggestion
const getDataUrl = (file: File): Promise<string> => {
```

2021-08-03 08:04 UTC, ghost commented on frontend/src/helpers/file/get-data-url/get-data-url.ts
> +  return new Promise((resolve) => {
```suggestion
  return new Promise((resolve, reject) => {
```

2021-08-03 08:04 UTC, ghost commented on frontend/src/helpers/file/get-data-url/get-data-url.ts
> +    fileReader.readAsDataURL(file);
```suggestion
    fileReader.addEventListener('load', () => {
      resolve(<string>fileReader.result)
    }, {
      once: true
    });
    
    fileReader.addEventListener('error', () => {
      reject(fileReader.error)
    }, {
      once: true
    });
    
    fileReader.readAsDataURL(file);
```

2021-08-03 08:04 UTC, ZubkoWhatislove commented on frontend/src/components/configurate-podcast/components/configurate-podcast-image/configurate-podcast-image.tsx
> +    const file = evt.currentTarget?.files?.[0];
```suggestion
    const [file] = evt.currentTarget?.files ?? [];
```

2021-08-03 08:04 UTC, ZubkoWhatislove commented on frontend/src/components/configurate-podcast/components/configurate-podcast-image/configurate-podcast-image.tsx
> +          accept=".jpg, .png, .svg"
create enum for it and also use it in the validation

2021-08-03 08:04 UTC, ZubkoWhatislove commented on frontend/src/common/types/types.ts
> +export type { Image } from './image/image';
```suggestion
```

2021-08-03 08:04 UTC, ZubkoWhatislove commented on frontend/src/common/types/image/image.ts
> +export type { Image } from 'jabber-shared/common/types/types';
remove file

2021-08-03 08:04 UTC, ZubkoWhatislove commented on backend/src/data/repositories/podcast/podcast.repository.ts
> +type PodcastRecordPayload = {
```suggestion
type PodcastCreateDTOPayload = {
```
move it to the common folder on the backend

2021-08-03 10:14 UTC, ZubkoWhatislove requested changes

2021-08-03 10:14 UTC, ZubkoWhatislove commented on backend/src/data/repositories/podcast/podcast.repository.ts
> +type PodcastCreateDTOPayload = {
move it to `backend/src/common/types`

2021-08-03 10:14 UTC, ZubkoWhatislove commented on frontend/src/components/configurate-podcast/components/configurate-podcast-image/configurate-podcast-image.tsx
> +  const fileMask = Object.values(ImageFileExtension).join(', ');
move it outside of the component

2021-08-03 11:42 UTC, ZubkoWhatislove requested changes

2021-08-03 11:42 UTC, ZubkoWhatislove commented on frontend/src/components/configurate-podcast/configurate-podcast.tsx
> +  const [imageSrc, setImageSrc] = useState('');
move stats before `handleCreatePodcast `

2021-08-03 13:02 UTC, merged