Task ys/j51 edit podcast functionality
BinaryStudioAcademy/bsa-2021-jabber pull request #69
Opened 2021-08-03 11:14 UTC by yaroslav207

2021-08-03 11:48 UTC, ZubkoWhatislove requested changes

2021-08-03 11:48 UTC, ZubkoWhatislove commented on frontend/src/store/configurate-podcast/reducer.ts
> +  editablePodcast: null,
```suggestion
};

const initialState: State = {
  dataStatus: DataStatus.IDLE,
  podcast: null,
```

2021-08-03 11:48 UTC, ZubkoWhatislove commented on frontend/src/services/podcast-api/podcast-api.service.ts
> +  public edit(id: number, payload: PodcastEditPayload): Promise<Podcast> {
```suggestion
  public edit(payload: PodcastEditPayload): Promise<Podcast> {
```

2021-08-03 11:48 UTC, ZubkoWhatislove commented on shared/src/common/enums/podcast/podcast-edit-payload-key.enum.ts
> +enum PodcastEditPayloadKey {
I think that we don't need and can use `Podcast` type instead

2021-08-03 11:48 UTC, ZubkoWhatislove commented on frontend/src/common/types/podcast/podcast-edit-action.type.ts
> +import { PodcastEditPayload } from './podcast';
not sure that we need it, we can use regular Podcast type

2021-08-03 11:48 UTC, ZubkoWhatislove commented on frontend/src/components/configurate-podcast/configurate-podcast.tsx
> +  };
```suggestion
  const handleFormSubmit = (payload: PodcastEditPayload): void => {
    const isEdit = Boolean(payload);
    isEdit ? dispatch(actions.edit(payload)) :  dispatch(actions.create(payload))

  };
```

2021-08-03 11:48 UTC, ZubkoWhatislove commented on frontend/src/services/podcast-api/podcast-api.service.ts
> +      `${this.#apiPrefix}${ApiPath.PODCASTS}${PodcastsApiPath.ROOT}${id}`,
```suggestion
      `${this.#apiPrefix}${ApiPath.PODCASTS}${PodcastsApiPath.ROOT}${payload.id}`,
```

2021-08-03 19:48 UTC, yevhenprybytok requested changes

2021-08-03 19:48 UTC, yevhenprybytok commented on frontend/src/components/configurate-podcast/configurate-podcast.tsx
> +  }, []);
Same code duplicated

2021-08-03 19:48 UTC, yevhenprybytok commented on frontend/src/components/configurate-podcast/configurate-podcast.tsx
> +    isEdit ? dispatch(configuratePodcastActions.edit(payload)) : dispatch(configuratePodcastActions.create(payload));
Create separate methods for those actions

2021-08-03 19:48 UTC, yevhenprybytok commented on frontend/src/components/configurate-podcast/configurate-podcast.tsx
> +      }
```suggestion
      <ConfiguratePodcastForm
          onSubmit={handleFormSubmit}
          payload={isEdit ? mappedPodcast : null}
       />
```
mappedPodcast - is the result of calling mapPodcastToFormPayload

2021-08-03 19:48 UTC, yevhenprybytok commented on frontend/src/store/configurate-podcast/actions.ts
> +  if(configuratePodcast.podcast){
```suggestion

  if (configuratePodcast.podcast) {
```

2021-08-04 14:54 UTC, ZubkoWhatislove requested changes

2021-08-04 14:54 UTC, ZubkoWhatislove commented on backend/src/services/podcast/podcast.service.ts
> +      const { url, publicId } = await this.#fileStorage.upload({
we need to delete the old image

2021-08-04 14:54 UTC, ZubkoWhatislove commented on frontend/src/components/configurate-podcast/components/configurate-podcast-form/configurate-podcast-form.tsx
> +  payload: PodcastFormPayload | undefined
```suggestion
  payload?: PodcastFormPayload
```

2021-08-04 14:54 UTC, ghost commented on frontend/src/components/configurate-podcast/configurate-podcast.tsx
> +  const mapPodcastToFormPayload = (podcast: Podcast): PodcastFormPayload => ({
move it to `frontend/src/components/configurate-podcast/helpers`

2021-08-04 14:54 UTC, ZubkoWhatislove commented on frontend/src/components/configurate-podcast/configurate-podcast.tsx
> +      {(!(dataStatus === 'pending')) && <ConfiguratePodcastForm onSubmit={handleFormSubmit} payload={mapPodcast}/>}
return loading

2021-08-04 14:54 UTC, ZubkoWhatislove commented on frontend/src/services/podcast-api/podcast-api.service.ts
> +import { PodcastEditPayload } from 'common/types/types';
move above

2021-08-04 14:54 UTC, ZubkoWhatislove commented on frontend/src/store/configurate-podcast/actions.ts
> +    const payloadEditPodcast = {
move it to function call

2021-08-04 14:54 UTC, ZubkoWhatislove commented on frontend/src/store/configurate-podcast/actions.ts
> +  return null;
```suggestion
```

2021-08-04 14:54 UTC, ZubkoWhatislove commented on frontend/src/store/configurate-podcast/actions.ts
> +const edit = createAsyncThunk<Podcast | null, PodcastFormPayload, AsyncThunkConfig>
```suggestion
const edit = createAsyncThunk<Podcast, PodcastFormPayload, AsyncThunkConfig>
```

2021-08-04 14:54 UTC, ZubkoWhatislove commented on shared/src/common/enums/podcast/podcast-edit-payload-key.enum.ts
> +enum PodcastEditPayloadKey {
remove it and use `podcast-payload-key.enum.ts `

2021-08-04 14:54 UTC, ZubkoWhatislove commented on shared/src/common/enums/podcast/podcast.ts
> +export { PodcastEditPayloadKey } from './podcast-edit-payload-key.enum';
```suggestion
```

2021-08-05 05:09 UTC, ZubkoWhatislove requested changes

2021-08-05 05:09 UTC, ZubkoWhatislove commented on backend/src/services/podcast/podcast.service.ts
> +      const { url, publicId } = await this.#fileStorage.upload({
don't fixed

2021-08-05 05:09 UTC, ZubkoWhatislove commented on frontend/src/components/configurate-podcast/configurate-podcast.tsx
> +      {(dataStatus === 'pending')
```suggestion
      {(dataStatus === DataStatus.PENDING)
```

2021-08-05 05:09 UTC, ZubkoWhatislove commented on frontend/src/helpers/file/parse-file/parse-file.ts
> +const parseFile = (payload: FileList | null): File => {
don't forget to change the filename
```suggestion
const getFileFromFileList = (payload: FileList | null): File => {
```

2021-08-05 05:09 UTC, ZubkoWhatislove commented on frontend/src/helpers/podcast/map-podcast-to-form-payload/map-podcast-to-form-payload.ts
> +import { Podcast, PodcastFormPayload } from 'common/types/types';
move it to helper to place where you use it

2021-08-05 05:09 UTC, ZubkoWhatislove commented on frontend/src/services/podcast-api/podcast-api.service.ts
> +  public edit(payload: PodcastEditPayload): Promise<Podcast> {
```suggestion
  public update(payload: PodcastEditPayload): Promise<Podcast> {
```

2021-08-05 05:09 UTC, ZubkoWhatislove commented on frontend/src/store/configurate-podcast/actions.ts
> +    const payloadEditPodcast = {
don't fixed

2021-08-05 10:26 UTC, ZubkoWhatislove requested changes

2021-08-05 10:26 UTC, ZubkoWhatislove commented on backend/src/data/repositories/image/image.repository.ts
> +    return this.#ImageModel.query().deleteById(payload);
```suggestion
  public delete(id: number): Promise<number> {
    return this.#ImageModel.query().deleteById(id);
```

2021-08-05 10:26 UTC, ZubkoWhatislove commented on frontend/src/components/configurate-podcast/configurate-podcast.tsx
> +
```suggestion
```

2021-08-05 10:26 UTC, ZubkoWhatislove commented on frontend/src/store/configurate-podcast/actions.ts
> +    return podcast;
```suggestion
   return podcastApi.update({
          ...updatePodcast,
      name: podcastPayload.name,
      description: podcastPayload.description,
      imageDataUrl: file ? await getDataUrl(file) : null,
    });
```

2021-08-05 15:14 UTC, ZubkoWhatislove approved these changes

2021-08-06 07:21 UTC, merged