Task yc/j70 add react select to our select component
BinaryStudioAcademy/bsa-2021-jabber pull request #71
Opened 2021-08-03 15:24 UTC by EugeniusGR

2021-08-03 18:03 UTC, EugeniusGR commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add react-select to our select component](https://trello.com/c/oX9Y9ilU/70-add-react-select-to-our-select-component)

2021-08-03 19:50 UTC, yevhenprybytok requested changes

2021-08-03 19:50 UTC, yevhenprybytok commented on frontend/src/components/common/select/select.tsx
> +import SelectReact from 'react-select';
Import order

2021-08-04 06:13 UTC, ZubkoWhatislove requested changes

2021-08-04 06:13 UTC, ZubkoWhatislove commented on frontend/package.json
> +    "react-select": "^4.3.1",
check **B17** criteria

2021-08-04 06:13 UTC, ZubkoWhatislove commented on frontend/package.json
> +    "@types/react-select": "^4.0.17",
check **B17** criteria

2021-08-04 06:13 UTC, ZubkoWhatislove commented on frontend/src/components/common/select/select.tsx
> +  options: string[];
now we need to create

```tsx
type Options = {
  label: string;
  value: string;
};
```
and use them for props for the select

2021-08-04 06:13 UTC, ZubkoWhatislove commented on frontend/src/components/common/select/select.tsx
> +        defaultValue={optionsItems[0]}
```suggestion
```

2021-08-04 08:42 UTC, ZubkoWhatislove requested changes

2021-08-04 08:42 UTC, ZubkoWhatislove commented on frontend/src/components/common/select/select.tsx
> +type Options = {
```suggestion
type Option = {
```
move it to `frontend/common/types/ui`

2021-08-04 08:42 UTC, ZubkoWhatislove commented on frontend/src/components/common/select/select.tsx
> +  options: string[];
```suggestion
  options: Option[];
```

2021-08-04 08:42 UTC, Denidzio submitted a review, later dismissed

2021-08-04 13:33 UTC, ZubkoWhatislove requested changes

2021-08-04 13:33 UTC, ZubkoWhatislove commented on frontend/src/components/configurate-episode/components/create-episode-form/create-episode-form.tsx
> +  const selectOptions:Option[] = Object.values(EpisodeType).map((item)=>{
create a helper for it
`getOptions(string[]) {}`

2021-08-04 14:46 UTC, ZubkoWhatislove approved these changes, later dismissed

2021-08-04 15:00 UTC, ZubkoWhatislove approved these changes

2021-08-04 15:01 UTC, merged