Task: vv/74 add shownotes table
BinaryStudioAcademy/bsa-2021-jabber pull request #76
Opened 2021-08-04 12:39 UTC by vitalik-prog

2021-08-04 13:36 UTC, ZubkoWhatislove requested changes
make shownotes as one word

2021-08-04 15:28 UTC, EugeniusGR approved these changes, later dismissed

2021-08-05 05:04 UTC, ZubkoWhatislove requested changes

2021-08-05 05:04 UTC, ZubkoWhatislove commented on backend/src/api/episodes/episodes.api.ts
> +      return res.send(response).status(HttpCode.OK);
remove back

2021-08-05 05:04 UTC, ZubkoWhatislove commented on backend/src/api/episodes/episodes.api.ts
> +  );
```suggestion
```

2021-08-05 05:04 UTC, ZubkoWhatislove commented on backend/src/common/enums/db/table-name.enum.ts
> +  SHOW_NOTES = 'show_notes',
```suggestion
  SHOWNOTES = 'shownotes',
```

2021-08-05 05:04 UTC, ZubkoWhatislove commented on backend/src/data/repositories/shownote/shownote.repository.ts
> +  public getAllTimeNotesByEpisodeId(id: string): Promise<TShownote[]> {
```suggestion
  public getAllByEpisodeId(id: string): Promise<TShownote[]> {
```

2021-08-05 05:04 UTC, ZubkoWhatislove commented on backend/src/services/shownote/shownote.service.ts
> +  public async getAllTimeNotesByEpisodeId(id: string): Promise<TShownote[]> {
```suggestion
  public async getAllByEpisodeId(id: string): Promise<TShownote[]> {
```

2021-08-05 05:04 UTC, ZubkoWhatislove commented on shared/src/common/enums/api/episodes-api-path.enum.ts
> +  TIMESTAMP = '/timestamp',
```suggestion
```

2021-08-05 12:59 UTC, ZubkoWhatislove requested changes

2021-08-05 12:59 UTC, ZubkoWhatislove commented on backend/src/api/episodes/episodes.api.ts
> +  episodeService: typeof episodeService,
```suggestion
  apiRouter: Router;
  episodeService: typeof episodeService;
```

2021-08-05 14:46 UTC, ZubkoWhatislove approved these changes

2021-08-06 07:17 UTC, merged