Make `+ Create Podcast` button as link in the header & add link to create episode to menu
BinaryStudioAcademy/bsa-2021-jabber pull request #79
Opened 2021-08-04 16:43 UTC by EugeniusGR

![image](https://user-images.githubusercontent.com/35200697/128220685-64d7a4e7-72d6-47ce-9ad9-44f6fec608c1.png)

2021-08-04 16:44 UTC, EugeniusGR commented
or maybe "Create Podacast" and "Create Episode" ?

2021-08-04 17:48 UTC, ZubkoWhatislove requested changes

2021-08-04 17:48 UTC, ZubkoWhatislove commented on frontend/src/common/enums/app/app-route.enum.ts
> +  EPISODE_EDIT = '/episodes/edit',
```suggestion
```

2021-08-04 17:48 UTC, ZubkoWhatislove commented on frontend/src/components/common/header/header.tsx
> +                          to={AppRoute.EPISODE_EDIT}
```suggestion
                          to={AppRoute.PODCAST_$ID_EPISODE_EDIT}
```

2021-08-04 19:19 UTC, qwiz1 approved these changes

2021-08-05 04:48 UTC, ZubkoWhatislove approved these changes

2021-08-05 04:49 UTC, merged