Task J-75. Add current user id as trace id in logger
BinaryStudioAcademy/bsa-2021-jabber pull request #82
Opened 2021-08-05 06:58 UTC by Denidzio

2021-08-05 08:32 UTC, ZubkoWhatislove requested changes

2021-08-05 08:32 UTC, ZubkoWhatislove commented on backend/src/middlewares/set-trace-id/set-trace-id.middleware.ts
> +  const bearerToken = authorizationHeader?.split(' ')[1];
what does 1 mean?

we already have this functionality in the current-user route

we need reuse it

2021-08-05 09:00 UTC, Denidzio commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add current user to `trace-id` in the logger middleware](https://trello.com/c/SQHzaLW3/75-add-current-user-to-trace-id-in-the-logger-middleware)

2021-08-05 15:38 UTC, ZubkoWhatislove requested changes

2021-08-05 15:38 UTC, ZubkoWhatislove commented on backend/src/helpers/jwt/extract-jwt-token/extract-jwt-token.helper.ts
> +  return token;
```suggestion
  const [, token] = header.split(' ');
  return token ?? null;
```

2021-08-05 15:38 UTC, ZubkoWhatislove commented on backend/src/helpers/jwt/extract-jwt-token/extract-jwt-token.helper.ts
> +const extractJwtToken = (header: string): string => {
```suggestion
const extractAuthToken = (header: string): string => {
```
don't forget to change the name of the file

2021-08-05 16:57 UTC, ZubkoWhatislove requested changes

2021-08-05 16:57 UTC, ZubkoWhatislove commented on backend/src/helpers/jwt/extract-auth-token/extract-auth-token.helper.ts
> +const extractAuthToken = (header: string | undefined): string | null => {
```suggestion
const extractAuthToken = (header?: string): string | null => {
```

2021-08-05 16:57 UTC, ZubkoWhatislove commented on backend/src/helpers/jwt/jwt.ts
> +export { extractAuthToken } from './extract-auth-token/extract-auth-token.helper';
backend/src/helpers/token/token.ts

2021-08-06 03:48 UTC, ZubkoWhatislove approved these changes

2021-08-06 07:03 UTC, yevhenprybytok approved these changes

2021-08-06 07:17 UTC, merged