J85: + enum-type-to-podcasts-table
BinaryStudioAcademy/bsa-2021-jabber pull request #85
Opened 2021-08-05 16:09 UTC by Sayonarko

2021-08-05 16:30 UTC, ghost requested changes
don't forget to change the model, type and etc

2021-08-05 16:30 UTC, ghost commented on backend/src/data/migrations/20210805155531_add_type_to_podcasts.ts
> +const PodcastsType = {
```suggestion
const PodcastType = {
```

2021-08-05 17:06 UTC, Denidzio approved these changes, later dismissed

2021-08-06 03:47 UTC, ZubkoWhatislove requested changes
Don't forget about model, type and etc

2021-08-06 07:10 UTC, yevhenprybytok approved these changes, later dismissed

2021-08-06 09:22 UTC, ZubkoWhatislove requested changes

2021-08-06 09:22 UTC, ZubkoWhatislove commented on backend/src/validation-schemas/podcast/create-podcast/create-podcast.validation-schema.ts
> +  [PodcastPayloadKey.TYPE]: Joi.string().valid(...Object.values(PodcastType)),
```suggestion
  const podcastTypes = Object.values(PodcastType);
  [PodcastPayloadKey.TYPE]: Joi.string().valid(...podcastTypes),
```

2021-08-07 08:33 UTC, merged