Tast as/j80 add datepicker custom library component
BinaryStudioAcademy/bsa-2021-jabber pull request #88
Opened 2021-08-05 19:12 UTC by qwiz1

2021-08-05 19:28 UTC, Denidzio approved these changes, later dismissed

2021-08-06 03:45 UTC, ZubkoWhatislove requested changes

2021-08-06 03:45 UTC, ZubkoWhatislove commented on frontend/src/components/common/datepicker/datepicker.tsx
> +        onChange={(date): void => field.onChange(date)}
avoid anonymous functions in the jsx

create a separate function for it

2021-08-06 07:13 UTC, yevhenprybytok approved these changes, later dismissed

2021-08-06 07:49 UTC, ZubkoWhatislove approved these changes

2021-08-06 07:49 UTC, merged