Task: vv/78 add white routes for our public routes
BinaryStudioAcademy/bsa-2021-jabber pull request #89
Opened 2021-08-05 20:33 UTC by vitalik-prog

2021-08-06 03:43 UTC, ZubkoWhatislove requested changes

2021-08-06 03:43 UTC, ZubkoWhatislove commented on backend/src/common/constants/routes/routes-white-list.ts
> +]);
use arrays of objects instead

2021-08-06 06:22 UTC, Denidzio submitted a review, later dismissed

2021-08-06 09:14 UTC, ZubkoWhatislove requested changes

2021-08-06 09:14 UTC, ZubkoWhatislove commented on backend/src/middlewares/authorization/authorization.middleware.ts
> +type WhiteRoute = {
move it to `backend/src/common/types`

2021-08-06 09:14 UTC, ZubkoWhatislove commented on backend/src/common/constants/routes/routes-white-list.ts
>  const ROUTES_WHITE_LIST = [
```suggestion
const ROUTES_WHITE_LIST: WhiteRoute[] = [
```

2021-08-06 09:15 UTC, ZubkoWhatislove requested changes

2021-08-06 09:15 UTC, ZubkoWhatislove commented on backend/src/middlewares/authorization/authorization.middleware.ts
> +const authorization = (routesWhiteList: Array<WhiteRoute> = []) => (
```suggestion
const authorization = (routesWhiteList: WhiteRoute[] = []) => (
```

2021-08-06 12:40 UTC, Sayonarko submitted a review, later dismissed

2021-08-08 09:56 UTC, what1s1ove requested changes

2021-08-08 09:56 UTC, what1s1ove commented on backend/src/middlewares/authorization/authorization.middleware.ts
> -import { Response, Request, NextFunction } from 'express';
rename the file

2021-08-08 10:13 UTC, merged