Task ys/j86 attach audio to episode functionality
BinaryStudioAcademy/bsa-2021-jabber pull request #94
Opened 2021-08-07 21:09 UTC by yaroslav207

2021-08-08 06:05 UTC, ZubkoWhatislove requested changes

2021-08-08 06:05 UTC, ghost commented on backend/src/api/episodes/episodes.api.ts
> +  episodeCreate as EpisodeValidationSchema,
```suggestion
  episodeCreate as episodeCreateValidationSchema,
```

2021-08-08 06:05 UTC, ghost commented on backend/src/common/enums/episode/episode-type.enum.ts
> -export { EpisodeType } from 'jabber-shared/common/enums/enums';
rename `backend/src/common/enums/episode/episode.ts`

2021-08-08 06:05 UTC, ghost commented on frontend/src/common/types/episode/episode-form-payload.type.ts
> +  [EpisodePayloadKey.PODCAST_ID]: number;
```suggestion
```
let's set it in the action

2021-08-08 06:05 UTC, ZubkoWhatislove commented on frontend/src/components/configurate-episode/components/create-episode-form/common/constants.ts
> +  [EpisodePayloadKey.PODCAST_ID]: DEFAULT_PODCAST_ID,
```suggestion
```

2021-08-08 06:05 UTC, ZubkoWhatislove commented on frontend/src/components/configurate-episode/components/create-episode-form/create-episode-form.tsx
> +  const acceptExtension = getFileExtensions(
move it from the component

2021-08-08 06:05 UTC, ZubkoWhatislove commented on shared/src/common/types/record/record-create-payload.type.ts
> +  [RecordCreatePayloadKey.PUBLIC_ID]: string;
good catch 👍

2021-08-08 07:17 UTC, yevhenprybytok approved these changes, later dismissed

2021-08-08 08:36 UTC, qwiz1 commented on frontend/src/validation-schemas/episode/create-episode/create-podcast.validation-schema.ts
> +import { Joi } from 'helpers/helpers';
frontend/src/validation-schemas/episode/create-episode/create-podcast.validation-schema.ts
This is probably a mistake in the schema file name. I think there must be:
frontend/src/validation-schemas/episode/create-episode/create-episode.validation-schema.ts

2021-08-08 10:47 UTC, Denidzio submitted a review, later dismissed

2021-08-09 05:13 UTC, ZubkoWhatislove approved these changes
👍

2021-08-09 05:14 UTC, merged